export async function previewAgentLoopSubmissionPlan({
  request,
  run,
  repositoryId,
  spaceId = null,
  instruction = '',
  maxSteps = 6,
  agentId = null,
  workspaceId = null,
  patchDryRunApprovalHandoffPreview = null,
  setSubmissionPlan = () => {},
}) {
  if (!repositoryId || !instruction.trim()) {
    setSubmissionPlan(null);
    return null;
  }
  const result = await run('code-agent-loop-submission-plan', async () => {
    const json = {
      repositoryId,
      spaceId,
      instruction: instruction.trim(),
      maxSteps,
      agentId,
      workspaceId,
    };
    if (patchDryRunApprovalHandoffPreview) {
      json.patchDryRunApprovalHandoffPreview = patchDryRunApprovalHandoffPreview;
    }
    const plan = await request('/api/code-agent/loop/submission-plan', {
      method: 'POST',
      json,
    });
    const review = plan?.patchDryRunApprovalReviewPreview || null;
    if (!review) {
      setSubmissionPlan(plan);
      return plan;
    }
    try {
      const approvalIntentPreview = await request('/api/code-agent/loop/runner/patch-dry-run-approval-intent-preview', {
        method: 'POST',
        json: {
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          patchDryRunApprovalReviewPreview: review,
        },
      });
      const approvalRequestCreationPreview = await request('/api/code-agent/loop/runner/patch-dry-run-approval-request-creation-preview', {
        method: 'POST',
        json: {
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          patchDryRunApprovalIntentPreview: approvalIntentPreview,
        },
      });
      const approvalDecisionPreview = await request('/api/code-agent/loop/runner/patch-dry-run-approval-decision-preview', {
        method: 'POST',
        json: {
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          patchDryRunApprovalRequestCreationPreview: approvalRequestCreationPreview,
        },
      });
      const approvalDecisionPersistencePreview = await request('/api/code-agent/loop/runner/patch-dry-run-approval-decision-persistence-preview', {
        method: 'POST',
        json: {
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          patchDryRunApprovalDecisionPreview: approvalDecisionPreview,
        },
      });
      const heldRequestReviewPreview = await request('/api/code-agent/loop/runner/patch-dry-run-held-request-review-preview', {
        method: 'POST',
        json: {
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          patchDryRunApprovalDecisionPersistencePreview: approvalDecisionPersistencePreview,
        },
      });
      const approvalActionPreview = await request('/api/code-agent/loop/runner/patch-dry-run-approval-action-preview', {
        method: 'POST',
        json: {
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          patchDryRunHeldRequestReviewPreview: heldRequestReviewPreview,
        },
      });
      const approvalActionPersistencePreview = await request('/api/code-agent/loop/runner/patch-dry-run-approval-action-persistence-preview', {
        method: 'POST',
        json: {
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          patchDryRunApprovalActionPreview: approvalActionPreview,
        },
      });
      const approvalRecordPreview = await request('/api/code-agent/loop/runner/patch-dry-run-approval-record-preview', {
        method: 'POST',
        json: {
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          patchDryRunApprovalActionPersistencePreview: approvalActionPersistencePreview,
        },
      });
      const localAgentRequestEnvelopePreview = await request('/api/code-agent/loop/runner/patch-dry-run-local-agent-request-envelope-preview', {
        method: 'POST',
        json: {
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          patchDryRunApprovalRecordPreview: approvalRecordPreview,
        },
      });
      const localAgentRequestCreationPreview = await request('/api/code-agent/loop/runner/patch-dry-run-local-agent-request-creation-preview', {
        method: 'POST',
        json: {
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          patchDryRunLocalAgentRequestEnvelopePreview: localAgentRequestEnvelopePreview,
        },
      });
      const localAgentQueuePreview = await request('/api/code-agent/loop/runner/patch-dry-run-local-agent-queue-preview', {
        method: 'POST',
        json: {
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          patchDryRunLocalAgentRequestCreationPreview: localAgentRequestCreationPreview,
        },
      });
      const localAgentClaimReadinessPreview = await request('/api/code-agent/loop/runner/patch-dry-run-local-agent-claim-readiness-preview', {
        method: 'POST',
        json: {
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          patchDryRunLocalAgentQueuePreview: localAgentQueuePreview,
        },
      });
      const localAgentSnapshotDryRunPreview = await request('/api/code-agent/loop/runner/patch-dry-run-local-agent-snapshot-dry-run-preview', {
        method: 'POST',
        json: {
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          patchDryRunLocalAgentClaimReadinessPreview: localAgentClaimReadinessPreview,
        },
      });
      const localAgentDryRunResultPreview = await request('/api/code-agent/loop/runner/patch-dry-run-local-agent-dry-run-result-preview', {
        method: 'POST',
        json: {
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          patchDryRunLocalAgentSnapshotDryRunPreview: localAgentSnapshotDryRunPreview,
        },
      });
      const localAgentRetryInputPreview = await request('/api/code-agent/loop/runner/patch-dry-run-local-agent-retry-input-preview', {
        method: 'POST',
        json: {
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          patchDryRunLocalAgentDryRunResultPreview: localAgentDryRunResultPreview,
        },
      });
      const localAgentRetryProposalPreview = await request('/api/code-agent/loop/runner/patch-dry-run-local-agent-retry-proposal-preview', {
        method: 'POST',
        json: {
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          patchDryRunLocalAgentRetryInputPreview: localAgentRetryInputPreview,
        },
      });
      const planWithIntent = {
        ...plan,
        patchDryRunApprovalIntentPreview: approvalIntentPreview,
        patchDryRunApprovalRequestCreationPreview: approvalRequestCreationPreview,
        patchDryRunApprovalDecisionPreview: approvalDecisionPreview,
        patchDryRunApprovalDecisionPersistencePreview: approvalDecisionPersistencePreview,
        patchDryRunHeldRequestReviewPreview: heldRequestReviewPreview,
        patchDryRunApprovalActionPreview: approvalActionPreview,
        patchDryRunApprovalActionPersistencePreview: approvalActionPersistencePreview,
        patchDryRunApprovalRecordPreview: approvalRecordPreview,
        patchDryRunLocalAgentRequestEnvelopePreview: localAgentRequestEnvelopePreview,
        patchDryRunLocalAgentRequestCreationPreview: localAgentRequestCreationPreview,
        patchDryRunLocalAgentQueuePreview: localAgentQueuePreview,
        patchDryRunLocalAgentClaimReadinessPreview: localAgentClaimReadinessPreview,
        patchDryRunLocalAgentSnapshotDryRunPreview: localAgentSnapshotDryRunPreview,
        patchDryRunLocalAgentDryRunResultPreview: localAgentDryRunResultPreview,
        patchDryRunLocalAgentRetryInputPreview: localAgentRetryInputPreview,
        patchDryRunLocalAgentRetryProposalPreview: localAgentRetryProposalPreview,
      };
      setSubmissionPlan(planWithIntent);
      return planWithIntent;
    } catch {
      const planWithIntentFallback = {
        ...plan,
        patchDryRunApprovalIntentPreview: {
          schema: 'learnbot.server.code-agent.patch-dry-run-approval-intent-preview.v1',
          status: 'APPROVAL_INTENT_PREVIEW_UNAVAILABLE',
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          reviewProvided: Boolean(review),
          approvalIntentPrepared: false,
          approvalIntentCreationEnabled: false,
          approvalPersistenceEnabled: false,
          requestCreationEnabled: false,
          approvalRequestCreationEnabled: false,
          enqueueEnabled: false,
          claimEnabled: false,
          snapshotCreationEnabled: false,
          patchDryRunExecutionEnabled: false,
          mutationEnabled: false,
          testExecutionEnabled: false,
          finalPublicationEnabled: false,
          partialReindexEnabled: false,
          approvalBypassAllowed: false,
          reason: 'Server approval-intent preview could not be loaded. No approval, request, queue, dry-run, mutation, publication, or reindex work was created.',
        },
        patchDryRunApprovalRequestCreationPreview: {
          schema: 'learnbot.server.code-agent.patch-dry-run-approval-request-creation-preview.v1',
          status: 'APPROVAL_REQUEST_CREATION_PREVIEW_UNAVAILABLE',
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          approvalIntentProvided: false,
          approvalRequestCreationPrepared: false,
          approvalPersistencePrepared: false,
          approvalPersistenceEnabled: false,
          approvalRequestCreationEnabled: false,
          requestCreationEnabled: false,
          serverApprovalRecordCreated: false,
          localAgentToolRequestCreated: false,
          enqueueEnabled: false,
          pushEnabled: false,
          claimEnabled: false,
          claimable: false,
          snapshotCreationEnabled: false,
          patchDryRunExecutionEnabled: false,
          mutationEnabled: false,
          testExecutionEnabled: false,
          rollbackRestoreEnabled: false,
          finalPublicationEnabled: false,
          partialReindexEnabled: false,
          approvalBypassAllowed: false,
          reason: 'Server approval request-creation preview could not be loaded. No approval, request, queue, dry-run, mutation, publication, or reindex work was created.',
        },
        patchDryRunApprovalDecisionPreview: {
          schema: 'learnbot.server.code-agent.patch-dry-run-approval-decision-preview.v1',
          status: 'APPROVAL_DECISION_PREVIEW_UNAVAILABLE',
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          approvalRequestCreationProvided: false,
          approvalDecisionPrepared: false,
          approvalDecisionPersistenceEnabled: false,
          approvalPersistenceEnabled: false,
          approvalRequestCreationEnabled: false,
          requestCreationEnabled: false,
          serverApprovalRecordCreated: false,
          approvalDecisionRecorded: false,
          localAgentToolRequestCreated: false,
          heldRequestCreated: false,
          enqueueEnabled: false,
          pushEnabled: false,
          claimEnabled: false,
          claimable: false,
          snapshotCreationEnabled: false,
          patchDryRunExecutionEnabled: false,
          mutationEnabled: false,
          testExecutionEnabled: false,
          rollbackRestoreEnabled: false,
          finalPublicationEnabled: false,
          partialReindexEnabled: false,
          approvalBypassAllowed: false,
          reason: 'Server approval decision preview could not be loaded. No approval, request, queue, dry-run, mutation, publication, or reindex work was created.',
        },
        patchDryRunApprovalDecisionPersistencePreview: {
          schema: 'learnbot.server.code-agent.patch-dry-run-approval-decision-persistence-preview.v1',
          status: 'APPROVAL_DECISION_PERSISTENCE_PREVIEW_UNAVAILABLE',
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          approvalDecisionProvided: false,
          approvalDecisionPersistencePrepared: false,
          heldRequestReviewPrepared: false,
          approvalDecisionPersistenceEnabled: false,
          approvalPersistenceEnabled: false,
          approvalRequestCreationEnabled: false,
          requestCreationEnabled: false,
          serverApprovalRecordCreated: false,
          approvalDecisionRecorded: false,
          approvalDecisionPersisted: false,
          localAgentToolRequestCreated: false,
          heldRequestCreated: false,
          enqueueEnabled: false,
          pushEnabled: false,
          claimEnabled: false,
          claimable: false,
          snapshotCreationEnabled: false,
          patchDryRunExecutionEnabled: false,
          mutationEnabled: false,
          testExecutionEnabled: false,
          rollbackRestoreEnabled: false,
          finalPublicationEnabled: false,
          partialReindexEnabled: false,
          approvalBypassAllowed: false,
          reason: 'Server approval decision persistence preview could not be loaded. No approval, request, queue, dry-run, mutation, publication, or reindex work was created.',
        },
        patchDryRunHeldRequestReviewPreview: {
          schema: 'learnbot.server.code-agent.patch-dry-run-held-request-review-action-preview.v1',
          status: 'HELD_REQUEST_REVIEW_PREVIEW_UNAVAILABLE',
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          approvalDecisionPersistenceProvided: false,
          heldRequestReviewActionPrepared: false,
          heldRequestReviewPrepared: false,
          heldRequestReviewEnabled: false,
          heldRequestCreated: false,
          approvalDecisionPersistenceEnabled: false,
          approvalPersistenceEnabled: false,
          approvalRequestCreationEnabled: false,
          requestCreationEnabled: false,
          serverApprovalRecordCreated: false,
          approvalDecisionRecorded: false,
          approvalDecisionPersisted: false,
          localAgentToolRequestCreated: false,
          enqueueEnabled: false,
          pushEnabled: false,
          claimEnabled: false,
          claimable: false,
          snapshotCreationEnabled: false,
          patchDryRunExecutionEnabled: false,
          mutationEnabled: false,
          testExecutionEnabled: false,
          rollbackRestoreEnabled: false,
          finalPublicationEnabled: false,
          partialReindexEnabled: false,
          approvalBypassAllowed: false,
          reason: 'Server held request review preview could not be loaded. No approval, request, queue, dry-run, mutation, publication, or reindex work was created.',
        },
        patchDryRunApprovalActionPreview: {
          schema: 'learnbot.server.code-agent.patch-dry-run-approval-action-preview.v1',
          status: 'APPROVAL_ACTION_PREVIEW_UNAVAILABLE',
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          heldRequestReviewProvided: false,
          approvalActionPrepared: false,
          heldRequestReviewPrepared: false,
          approvalActionEnabled: false,
          heldRequestReviewEnabled: false,
          heldRequestCreated: false,
          approvalDecisionPersistenceEnabled: false,
          approvalPersistenceEnabled: false,
          approvalRequestCreationEnabled: false,
          requestCreationEnabled: false,
          serverApprovalRecordCreated: false,
          approvalDecisionRecorded: false,
          approvalDecisionPersisted: false,
          approvalActionRecorded: false,
          approvalActionPersisted: false,
          localAgentToolRequestCreated: false,
          enqueueEnabled: false,
          pushEnabled: false,
          claimEnabled: false,
          claimable: false,
          snapshotCreationEnabled: false,
          patchDryRunExecutionEnabled: false,
          mutationEnabled: false,
          testExecutionEnabled: false,
          rollbackRestoreEnabled: false,
          finalPublicationEnabled: false,
          partialReindexEnabled: false,
          approvalBypassAllowed: false,
          reason: 'Server approval action preview could not be loaded. No approval, request, queue, dry-run, mutation, publication, or reindex work was created.',
        },
        patchDryRunApprovalActionPersistencePreview: {
          schema: 'learnbot.server.code-agent.patch-dry-run-approval-action-persistence-preview.v1',
          status: 'APPROVAL_ACTION_PERSISTENCE_PREVIEW_UNAVAILABLE',
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          approvalActionProvided: false,
          approvalActionPersistencePrepared: false,
          heldRequestReviewPrepared: false,
          approvalActionPersistenceEnabled: false,
          approvalActionEnabled: false,
          heldRequestReviewEnabled: false,
          heldRequestCreated: false,
          approvalDecisionPersistenceEnabled: false,
          approvalPersistenceEnabled: false,
          approvalRequestCreationEnabled: false,
          requestCreationEnabled: false,
          serverApprovalRecordCreated: false,
          approvalDecisionRecorded: false,
          approvalDecisionPersisted: false,
          approvalActionRecorded: false,
          approvalActionPersisted: false,
          localAgentToolRequestCreated: false,
          enqueueEnabled: false,
          pushEnabled: false,
          claimEnabled: false,
          claimable: false,
          snapshotCreationEnabled: false,
          patchDryRunExecutionEnabled: false,
          mutationEnabled: false,
          testExecutionEnabled: false,
          rollbackRestoreEnabled: false,
          finalPublicationEnabled: false,
          partialReindexEnabled: false,
          approvalBypassAllowed: false,
          reason: 'Server approval action persistence preview could not be loaded. No approval, request, queue, dry-run, mutation, publication, or reindex work was created.',
        },
        patchDryRunApprovalRecordPreview: {
          schema: 'learnbot.server.code-agent.patch-dry-run-approval-record-preview.v1',
          status: 'APPROVAL_RECORD_PREVIEW_UNAVAILABLE',
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          approvalActionPersistenceProvided: false,
          approvalRecordPrepared: false,
          localAgentRequestCreationPrepared: false,
          approvalRecordCreationEnabled: false,
          approvalActionPersistenceEnabled: false,
          approvalActionEnabled: false,
          heldRequestReviewEnabled: false,
          heldRequestCreated: false,
          approvalDecisionPersistenceEnabled: false,
          approvalPersistenceEnabled: false,
          approvalRequestCreationEnabled: false,
          requestCreationEnabled: false,
          serverApprovalRecordCreated: false,
          approvalDecisionRecorded: false,
          approvalDecisionPersisted: false,
          approvalActionRecorded: false,
          approvalActionPersisted: false,
          localAgentToolRequestCreated: false,
          enqueueEnabled: false,
          pushEnabled: false,
          claimEnabled: false,
          claimable: false,
          snapshotCreationEnabled: false,
          patchDryRunExecutionEnabled: false,
          mutationEnabled: false,
          testExecutionEnabled: false,
          rollbackRestoreEnabled: false,
          finalPublicationEnabled: false,
          partialReindexEnabled: false,
          approvalBypassAllowed: false,
          reason: 'Server approval record preview could not be loaded. No approval, request, queue, dry-run, mutation, publication, or reindex work was created.',
        },
        patchDryRunLocalAgentRequestEnvelopePreview: {
          schema: 'learnbot.server.code-agent.patch-dry-run-local-agent-request-envelope-preview.v1',
          status: 'LOCAL_AGENT_REQUEST_ENVELOPE_PREVIEW_UNAVAILABLE',
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          approvalRecordProvided: false,
          localAgentRequestEnvelopePrepared: false,
          localAgentRequestCreationPrepared: false,
          approvalRecordCreationEnabled: false,
          approvalActionPersistenceEnabled: false,
          approvalActionEnabled: false,
          heldRequestReviewEnabled: false,
          heldRequestCreated: false,
          approvalDecisionPersistenceEnabled: false,
          approvalPersistenceEnabled: false,
          approvalRequestCreationEnabled: false,
          requestCreationEnabled: false,
          serverApprovalRecordCreated: false,
          approvalDecisionRecorded: false,
          approvalDecisionPersisted: false,
          approvalActionRecorded: false,
          approvalActionPersisted: false,
          localAgentToolRequestCreated: false,
          enqueueEnabled: false,
          pushEnabled: false,
          claimEnabled: false,
          claimable: false,
          snapshotCreationEnabled: false,
          patchDryRunExecutionEnabled: false,
          mutationEnabled: false,
          testExecutionEnabled: false,
          rollbackRestoreEnabled: false,
          finalPublicationEnabled: false,
          partialReindexEnabled: false,
          approvalBypassAllowed: false,
          reason: 'Server Local Agent request envelope preview could not be loaded. No request, queue, dry-run, mutation, publication, or reindex work was created.',
        },
        patchDryRunLocalAgentRequestCreationPreview: {
          schema: 'learnbot.server.code-agent.patch-dry-run-local-agent-request-creation-preview.v1',
          status: 'LOCAL_AGENT_REQUEST_CREATION_PREVIEW_UNAVAILABLE',
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          localAgentRequestEnvelopeProvided: false,
          localAgentRequestEnvelopePrepared: false,
          localAgentRequestCreationPrepared: false,
          queueHandoffPrepared: false,
          approvalRecordCreationEnabled: false,
          approvalActionPersistenceEnabled: false,
          approvalActionEnabled: false,
          heldRequestReviewEnabled: false,
          heldRequestCreated: false,
          approvalDecisionPersistenceEnabled: false,
          approvalPersistenceEnabled: false,
          approvalRequestCreationEnabled: false,
          requestCreationEnabled: false,
          serverApprovalRecordCreated: false,
          approvalDecisionRecorded: false,
          approvalDecisionPersisted: false,
          approvalActionRecorded: false,
          approvalActionPersisted: false,
          localAgentToolRequestCreated: false,
          durableLocalAgentRequestCreated: false,
          enqueueEnabled: false,
          pushEnabled: false,
          claimEnabled: false,
          claimable: false,
          snapshotCreationEnabled: false,
          patchDryRunExecutionEnabled: false,
          mutationEnabled: false,
          testExecutionEnabled: false,
          rollbackRestoreEnabled: false,
          finalPublicationEnabled: false,
          partialReindexEnabled: false,
          approvalBypassAllowed: false,
          reason: 'Server Local Agent request creation preview could not be loaded. No request, queue, dry-run, mutation, publication, or reindex work was created.',
        },
        patchDryRunLocalAgentQueuePreview: {
          schema: 'learnbot.server.code-agent.patch-dry-run-local-agent-queue-preview.v1',
          status: 'LOCAL_AGENT_QUEUE_PREVIEW_UNAVAILABLE',
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          localAgentRequestCreationProvided: false,
          localAgentRequestCreationPrepared: false,
          queueHandoffPrepared: false,
          pushHandoffPrepared: false,
          claimHandoffPrepared: false,
          approvalRecordCreationEnabled: false,
          approvalActionPersistenceEnabled: false,
          approvalActionEnabled: false,
          heldRequestReviewEnabled: false,
          heldRequestCreated: false,
          approvalDecisionPersistenceEnabled: false,
          approvalPersistenceEnabled: false,
          approvalRequestCreationEnabled: false,
          requestCreationEnabled: false,
          serverApprovalRecordCreated: false,
          approvalDecisionRecorded: false,
          approvalDecisionPersisted: false,
          approvalActionRecorded: false,
          approvalActionPersisted: false,
          localAgentToolRequestCreated: false,
          durableLocalAgentRequestCreated: false,
          enqueueEnabled: false,
          pushEnabled: false,
          claimEnabled: false,
          claimable: false,
          snapshotCreationEnabled: false,
          patchDryRunExecutionEnabled: false,
          mutationEnabled: false,
          testExecutionEnabled: false,
          rollbackRestoreEnabled: false,
          finalPublicationEnabled: false,
          partialReindexEnabled: false,
          approvalBypassAllowed: false,
          reason: 'Server Local Agent queue preview could not be loaded. No request, queue, dry-run, mutation, publication, or reindex work was created.',
        },
        patchDryRunLocalAgentClaimReadinessPreview: {
          schema: 'learnbot.server.code-agent.patch-dry-run-local-agent-claim-readiness-preview.v1',
          status: 'LOCAL_AGENT_CLAIM_READINESS_PREVIEW_UNAVAILABLE',
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          localAgentQueueProvided: false,
          queueHandoffPrepared: false,
          pushHandoffPrepared: false,
          claimHandoffPrepared: false,
          snapshotDryRunReadinessPrepared: false,
          approvalRecordCreationEnabled: false,
          approvalActionPersistenceEnabled: false,
          approvalActionEnabled: false,
          heldRequestReviewEnabled: false,
          heldRequestCreated: false,
          approvalDecisionPersistenceEnabled: false,
          approvalPersistenceEnabled: false,
          approvalRequestCreationEnabled: false,
          requestCreationEnabled: false,
          serverApprovalRecordCreated: false,
          approvalDecisionRecorded: false,
          approvalDecisionPersisted: false,
          approvalActionRecorded: false,
          approvalActionPersisted: false,
          localAgentToolRequestCreated: false,
          durableLocalAgentRequestCreated: false,
          enqueueEnabled: false,
          pushEnabled: false,
          claimEnabled: false,
          claimable: false,
          snapshotCreationEnabled: false,
          patchDryRunExecutionEnabled: false,
          mutationEnabled: false,
          testExecutionEnabled: false,
          rollbackRestoreEnabled: false,
          finalPublicationEnabled: false,
          partialReindexEnabled: false,
          approvalBypassAllowed: false,
          reason: 'Server Local Agent claim readiness preview could not be loaded. No claim, snapshot dry-run, mutation, publication, or reindex work was created.',
        },
        patchDryRunLocalAgentSnapshotDryRunPreview: {
          schema: 'learnbot.server.code-agent.patch-dry-run-local-agent-snapshot-dry-run-preview.v1',
          status: 'LOCAL_AGENT_SNAPSHOT_DRY_RUN_PREVIEW_UNAVAILABLE',
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          localAgentClaimReadinessProvided: false,
          queueHandoffPrepared: false,
          pushHandoffPrepared: false,
          claimHandoffPrepared: false,
          snapshotDryRunReadinessPrepared: false,
          patchDryRunExecutionObservationPrepared: false,
          approvalRecordCreationEnabled: false,
          approvalActionPersistenceEnabled: false,
          approvalActionEnabled: false,
          heldRequestReviewEnabled: false,
          heldRequestCreated: false,
          approvalDecisionPersistenceEnabled: false,
          approvalPersistenceEnabled: false,
          approvalRequestCreationEnabled: false,
          requestCreationEnabled: false,
          serverApprovalRecordCreated: false,
          approvalDecisionRecorded: false,
          approvalDecisionPersisted: false,
          approvalActionRecorded: false,
          approvalActionPersisted: false,
          localAgentToolRequestCreated: false,
          durableLocalAgentRequestCreated: false,
          enqueueEnabled: false,
          pushEnabled: false,
          claimEnabled: false,
          claimable: false,
          snapshotCreationEnabled: false,
          patchDryRunExecutionEnabled: false,
          patchDryRunExecuted: false,
          patchDryRunObservationRecorded: false,
          mutationEnabled: false,
          testExecutionEnabled: false,
          rollbackRestoreEnabled: false,
          finalPublicationEnabled: false,
          partialReindexEnabled: false,
          approvalBypassAllowed: false,
          reason: 'Server Local Agent snapshot dry-run preview could not be loaded. No claim, snapshot dry-run, observation, mutation, publication, or reindex work was created.',
        },
        patchDryRunLocalAgentDryRunResultPreview: {
          schema: 'learnbot.server.code-agent.patch-dry-run-local-agent-dry-run-result-preview.v1',
          status: 'LOCAL_AGENT_DRY_RUN_RESULT_PREVIEW_UNAVAILABLE',
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          localAgentSnapshotDryRunProvided: false,
          snapshotDryRunReadinessPrepared: false,
          patchDryRunExecutionObservationPrepared: false,
          dryRunResultAnalysisPrepared: false,
          failureLogAnalysisPrepared: false,
          retryDecisionPrepared: false,
          dryRunResultStatus: 'UNAVAILABLE',
          dryRunFailureCode: 'NO_RESULT',
          dryRunSucceeded: false,
          dryRunFailed: false,
          contextMismatchDetected: false,
          unsafePatchDetected: false,
          retryRecommended: false,
          retryDecision: 'WAIT_FOR_SNAPSHOT_DRY_RUN_PREVIEW',
          replanRequired: false,
          userReviewRequired: false,
          approvalRecordCreationEnabled: false,
          approvalActionPersistenceEnabled: false,
          approvalActionEnabled: false,
          heldRequestReviewEnabled: false,
          heldRequestCreated: false,
          approvalDecisionPersistenceEnabled: false,
          approvalPersistenceEnabled: false,
          approvalRequestCreationEnabled: false,
          requestCreationEnabled: false,
          serverApprovalRecordCreated: false,
          approvalDecisionRecorded: false,
          approvalDecisionPersisted: false,
          approvalActionRecorded: false,
          approvalActionPersisted: false,
          localAgentToolRequestCreated: false,
          durableLocalAgentRequestCreated: false,
          enqueueEnabled: false,
          pushEnabled: false,
          claimEnabled: false,
          claimable: false,
          snapshotCreationEnabled: false,
          patchDryRunExecutionEnabled: false,
          patchDryRunExecuted: false,
          patchDryRunObservationRecorded: false,
          dryRunResultRecorded: false,
          failureLogAnalysisRecorded: false,
          retryDecisionRecorded: false,
          mutationEnabled: false,
          testExecutionEnabled: false,
          rollbackRestoreEnabled: false,
          finalPublicationEnabled: false,
          partialReindexEnabled: false,
          approvalBypassAllowed: false,
          reason: 'Server Local Agent dry-run result preview could not be loaded. No dry-run result, failure-log analysis, retry, mutation, publication, or reindex work was created.',
        },
        patchDryRunLocalAgentRetryInputPreview: {
          schema: 'learnbot.server.code-agent.patch-dry-run-local-agent-retry-input-preview.v1',
          status: 'LOCAL_AGENT_RETRY_INPUT_PREVIEW_UNAVAILABLE',
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          localAgentDryRunResultProvided: false,
          retryInputPrepared: false,
          boundedRetryPatchInputPrepared: false,
          replanDecisionPrepared: false,
          dryRunResultStatus: 'UNAVAILABLE',
          dryRunFailureCode: 'NO_RESULT',
          contextMismatchDetected: false,
          unsafePatchDetected: false,
          retryRecommended: false,
          sourceRetryDecision: 'WAIT_FOR_DRY_RUN_RESULT_PREVIEW',
          retryInputDecision: 'WAIT_FOR_DRY_RUN_RESULT_PREVIEW',
          replanRequired: false,
          userVisibleDecision: 'WAIT_FOR_DRY_RUN_RESULT_PREVIEW',
          approvalRecordCreationEnabled: false,
          approvalActionPersistenceEnabled: false,
          approvalActionEnabled: false,
          heldRequestReviewEnabled: false,
          heldRequestCreated: false,
          approvalDecisionPersistenceEnabled: false,
          approvalPersistenceEnabled: false,
          approvalRequestCreationEnabled: false,
          requestCreationEnabled: false,
          serverApprovalRecordCreated: false,
          approvalDecisionRecorded: false,
          approvalDecisionPersisted: false,
          approvalActionRecorded: false,
          approvalActionPersisted: false,
          localAgentToolRequestCreated: false,
          durableLocalAgentRequestCreated: false,
          enqueueEnabled: false,
          pushEnabled: false,
          claimEnabled: false,
          claimable: false,
          snapshotCreationEnabled: false,
          patchDryRunExecutionEnabled: false,
          patchDryRunExecuted: false,
          patchDryRunObservationRecorded: false,
          dryRunResultRecorded: false,
          failureLogAnalysisRecorded: false,
          retryDecisionRecorded: false,
          retryPatchGenerated: false,
          retryRequestCreationEnabled: false,
          retryExecutionEnabled: false,
          replanExecutionEnabled: false,
          mutationEnabled: false,
          testExecutionEnabled: false,
          rollbackRestoreEnabled: false,
          finalPublicationEnabled: false,
          partialReindexEnabled: false,
          approvalBypassAllowed: false,
          reason: 'Server Local Agent retry input preview could not be loaded. No retry input, replan, mutation, publication, or reindex work was created.',
        },
        patchDryRunLocalAgentRetryProposalPreview: {
          schema: 'learnbot.server.code-agent.patch-dry-run-local-agent-retry-proposal-preview.v1',
          status: 'LOCAL_AGENT_RETRY_PROPOSAL_PREVIEW_UNAVAILABLE',
          repositoryId,
          spaceId,
          agentId,
          workspaceId,
          localAgentRetryInputProvided: false,
          retryProposalPrepared: false,
          boundedRetryPatchProposalPrepared: false,
          finalStopDecisionPrepared: false,
          dryRunResultStatus: 'UNAVAILABLE',
          dryRunFailureCode: 'NO_RESULT',
          contextMismatchDetected: false,
          unsafePatchDetected: false,
          retryRecommended: false,
          sourceRetryInputDecision: 'WAIT_FOR_RETRY_INPUT_PREVIEW',
          replanRequired: false,
          userVisibleDecision: 'WAIT_FOR_RETRY_INPUT_PREVIEW',
          finalStopDecision: 'WAIT_FOR_RETRY_INPUT_PREVIEW',
          approvalRecordCreationEnabled: false,
          approvalActionPersistenceEnabled: false,
          approvalActionEnabled: false,
          heldRequestReviewEnabled: false,
          heldRequestCreated: false,
          approvalDecisionPersistenceEnabled: false,
          approvalPersistenceEnabled: false,
          approvalRequestCreationEnabled: false,
          requestCreationEnabled: false,
          serverApprovalRecordCreated: false,
          approvalDecisionRecorded: false,
          approvalDecisionPersisted: false,
          approvalActionRecorded: false,
          approvalActionPersisted: false,
          localAgentToolRequestCreated: false,
          durableLocalAgentRequestCreated: false,
          enqueueEnabled: false,
          pushEnabled: false,
          claimEnabled: false,
          claimable: false,
          snapshotCreationEnabled: false,
          patchDryRunExecutionEnabled: false,
          patchDryRunExecuted: false,
          patchDryRunObservationRecorded: false,
          dryRunResultRecorded: false,
          failureLogAnalysisRecorded: false,
          retryDecisionRecorded: false,
          retryPatchGenerated: false,
          retryPatchProposalGenerated: false,
          retryRequestCreationEnabled: false,
          retryExecutionEnabled: false,
          replanExecutionEnabled: false,
          mutationEnabled: false,
          testExecutionEnabled: false,
          rollbackRestoreEnabled: false,
          finalPublicationEnabled: false,
          partialReindexEnabled: false,
          approvalBypassAllowed: false,
          reason: 'Server Local Agent retry proposal preview could not be loaded. No retry patch proposal, final-stop decision, mutation, publication, or reindex work was created.',
        },
      };
      setSubmissionPlan(planWithIntentFallback);
      return planWithIntentFallback;
    }
  });
  if (result === false) {
    setSubmissionPlan(null);
    return null;
  }
  return result;
}
