import assert from 'node:assert/strict';
import { buildAgentLoopTimelineHistoryView } from './agentLoopTimelineSummary.js';

const view = buildAgentLoopTimelineHistoryView([
  {
    id: 'loop-1',
    status: 'PREVIEW_ONLY',
    maxSteps: 6,
    timeoutSeconds: 120,
    mutationEnabled: false,
    timelinePersistenceEnabled: true,
    cancellationEnabled: false,
    instruction: 'fix parser bug',
    createdAt: '2026-06-30T12:00:00Z',
    events: [
      {
        sequenceNumber: 1,
        eventType: 'LOOP_PREVIEW_CREATED',
        requiresApproval: false,
        mayMutate: false,
        enabled: false,
        details: {},
      },
      {
        sequenceNumber: 3,
        eventType: 'APPROVAL_CHECKPOINT_PREVIEW',
        phase: 'REQUEST_APPROVAL',
        executionTarget: 'USER_LOCAL_AGENT',
        toolName: 'patch.apply',
        requiresApproval: true,
        mayMutate: false,
        enabled: true,
        details: {
          action: 'Require explicit user approval before any side-effectful tool can run.',
        },
      },
      {
        sequenceNumber: 8,
        eventType: 'TIMEOUT_POLICY_REGISTERED',
        requiresApproval: false,
        mayMutate: false,
        enabled: false,
        details: {
          status: 'REGISTERED',
          timeoutSeconds: 120,
        },
      },
      {
        sequenceNumber: 9,
        eventType: 'CANCELLATION_POLICY_REGISTERED',
        requiresApproval: false,
        mayMutate: false,
        enabled: false,
        details: {
          status: 'DISABLED',
          cancellationEnabled: false,
        },
      },
      {
        sequenceNumber: 10,
        eventType: 'FINAL_RESULT_POLICY_REGISTERED',
        requiresApproval: false,
        mayMutate: false,
        enabled: false,
        details: {
          status: 'PENDING_PREVIEW_ONLY',
          finalResultEnabled: false,
        },
      },
      {
        sequenceNumber: 11,
        eventType: 'STOP_OUTCOME_POLICY_REGISTERED',
        requiresApproval: false,
        mayMutate: false,
        enabled: false,
        details: {
          status: 'REGISTERED',
          stopKey: 'WEAK_EVIDENCE',
          outcome: 'ASK_FOR_CLARIFICATION',
        },
      },
      {
        sequenceNumber: 12,
        eventType: 'STOP_OUTCOME_POLICY_REGISTERED',
        requiresApproval: false,
        mayMutate: false,
        enabled: false,
        details: {
          status: 'REGISTERED',
          stopKey: 'AGENT_UNAVAILABLE',
          outcome: 'WAIT_FOR_LOCAL_AGENT',
        },
      },
      {
        sequenceNumber: 13,
        eventType: 'STOP_OUTCOME_POLICY_REGISTERED',
        requiresApproval: false,
        mayMutate: false,
        enabled: false,
        details: {
          status: 'REGISTERED',
          stopKey: 'TOOL_FAILED',
          outcome: 'REPORT_TOOL_FAILURE',
        },
      },
      {
        sequenceNumber: 14,
        eventType: 'STOP_OUTCOME_POLICY_REGISTERED',
        requiresApproval: false,
        mayMutate: false,
        enabled: false,
        details: {
          status: 'REGISTERED',
          stopKey: 'APPROVAL_DENIED',
          outcome: 'REPORT_APPROVAL_DENIED',
        },
      },
      {
        sequenceNumber: 15,
        eventType: 'LOCAL_AGENT_OBSERVATION_RESULT',
        phase: 'OBSERVE',
        executionTarget: 'USER_LOCAL_AGENT',
        toolName: 'patch.apply',
        requiresApproval: true,
        mayMutate: false,
        enabled: true,
        details: {
          status: 'SUCCEEDED',
          freshObservationOnly: true,
          dryRun: true,
          mutationApplied: false,
        },
      },
      {
        sequenceNumber: 16,
        eventType: 'LOCAL_AGENT_APPROVAL_DECISION',
        phase: 'REQUEST_APPROVAL',
        executionTarget: 'USER_LOCAL_AGENT',
        toolName: 'patch.apply',
        requiresApproval: true,
        mayMutate: false,
        enabled: true,
        details: {
          status: 'APPROVED_HELD',
          approvalState: 'APPROVED',
          recommendedAction: {
            schema: 'learnbot.code-agent.runner-recommended-action.v1',
            actionKey: 'CHECK_ENQUEUE_REFUSAL',
            label: 'Check enqueue refusal',
            enabled: true,
            method: 'POST',
            endpoint: '/api/code-agent/loop/runner/enqueue-read-only',
            requestCreationEnabled: false,
            pushEnabled: false,
            claimEnabled: false,
            mutationEnabled: false,
            reason: 'Confirm the runner will not enqueue mutation work from this handoff state.',
          },
        },
      },
      {
        sequenceNumber: 17,
        eventType: 'LOCAL_AGENT_APPROVAL_REQUEST_CREATED',
        phase: 'REQUEST_APPROVAL',
        executionTarget: 'USER_LOCAL_AGENT',
        toolName: 'patch.apply',
        requiresApproval: true,
        mayMutate: false,
        enabled: true,
        details: {
          status: 'APPROVAL_REQUIRED',
          approvalState: 'REQUIRED',
          validatedDryRunIntent: true,
          dryRunIntentPersisted: true,
          reviewSurface: 'CODE_WORKSPACE_LOOP_REVIEW',
          requestPersisted: true,
          queueEnabled: false,
          pushEnabled: false,
          claimable: false,
          dryRunOnly: true,
          mutationAllowed: false,
          dryRunIntentReviewRequired: true,
          recommendedAction: {
            actionKey: 'WAIT_FOR_APPROVAL',
            label: 'Wait for approval',
            enabled: true,
            requestCreationEnabled: false,
            pushEnabled: false,
            claimEnabled: false,
            mutationEnabled: false,
            reason: 'Review the persisted validated dry-run intent before any future claimable non-mutating dry-run.',
          },
        },
      },
      {
        sequenceNumber: 18,
        eventType: 'STOP_OUTCOME_RECORDED',
        phase: 'COMPLETE_OR_PAUSE',
        requiresApproval: false,
        mayMutate: false,
        enabled: true,
        details: {
          status: 'RECORDED',
          stopKey: 'TOOL_FAILED',
          outcome: 'REPORT_TOOL_FAILURE',
          finalResultEnabled: false,
        },
      },
      {
        sequenceNumber: 19,
        eventType: 'STOP_OUTCOME_RECORDED',
        phase: 'COMPLETE_OR_PAUSE',
        requiresApproval: false,
        mayMutate: false,
        enabled: true,
        details: {
          status: 'RECORDED',
          stopKey: 'APPROVAL_DENIED',
          outcome: 'REPORT_APPROVAL_DENIED',
          finalResultEnabled: false,
        },
      },
      {
        sequenceNumber: 20,
        eventType: 'STOP_OUTCOME_RECORDED',
        phase: 'COMPLETE_OR_PAUSE',
        requiresApproval: false,
        mayMutate: false,
        enabled: true,
        details: {
          status: 'RECORDED',
          stopKey: 'AGENT_UNAVAILABLE',
          outcome: 'WAIT_FOR_LOCAL_AGENT',
          finalResultEnabled: false,
        },
      },
      {
        sequenceNumber: 21,
        eventType: 'STOP_OUTCOME_RECORDED',
        phase: 'COMPLETE_OR_PAUSE',
        requiresApproval: false,
        mayMutate: false,
        enabled: true,
        details: {
          status: 'RECORDED',
          stopKey: 'TIMEOUT',
          outcome: 'REPORT_TIMEOUT',
          finalResultEnabled: false,
        },
      },
      {
        sequenceNumber: 22,
        eventType: 'STOP_OUTCOME_RECORDED',
        phase: 'COMPLETE_OR_PAUSE',
        requiresApproval: false,
        mayMutate: false,
        enabled: true,
        details: {
          status: 'RECORDED',
          stopKey: 'CANCELLATION',
          outcome: 'REPORT_CANCELLATION',
          finalResultEnabled: false,
        },
      },
    ],
  },
]);

assert.equal(view.headerText, '에이전트 루프 실행 이력: 1');
assert.equal(view.helperText, '문제 원인 추적용 상세 로그입니다. 평소에는 접어두어도 됩니다.');
assert.equal(view.timelines[0].headerText, 'loop timeline: PREVIEW_ONLY / max steps 6 / timeout 120s');
assert.equal(view.timelines[0].stateText, 'timeline state: mutation false / persistence true / cancellation false');
assert.equal(view.timelines[0].instructionText, 'instruction: fix parser bug');
assert.deepEqual(view.timelines[0].eventLines, [
  '1 LOOP_PREVIEW_CREATED / approval false / may mutate false / enabled false',
  '3 APPROVAL_CHECKPOINT_PREVIEW / REQUEST_APPROVAL / USER_LOCAL_AGENT / patch.apply / approval true / may mutate false / enabled true / action: Require explicit user approval before any side-effectful tool can run.',
  '8 TIMEOUT_POLICY_REGISTERED / approval false / may mutate false / enabled false / status REGISTERED / timeout 120s',
  '9 CANCELLATION_POLICY_REGISTERED / approval false / may mutate false / enabled false / status DISABLED / cancellation false',
  '10 FINAL_RESULT_POLICY_REGISTERED / approval false / may mutate false / enabled false / status PENDING_PREVIEW_ONLY / final result false',
  '11 STOP_OUTCOME_POLICY_REGISTERED / approval false / may mutate false / enabled false / status REGISTERED / stop WEAK_EVIDENCE / outcome ASK_FOR_CLARIFICATION',
  '12 STOP_OUTCOME_POLICY_REGISTERED / approval false / may mutate false / enabled false / status REGISTERED / stop AGENT_UNAVAILABLE / outcome WAIT_FOR_LOCAL_AGENT',
  '13 STOP_OUTCOME_POLICY_REGISTERED / approval false / may mutate false / enabled false / status REGISTERED / stop TOOL_FAILED / outcome REPORT_TOOL_FAILURE',
  '14 STOP_OUTCOME_POLICY_REGISTERED / approval false / may mutate false / enabled false / status REGISTERED / stop APPROVAL_DENIED / outcome REPORT_APPROVAL_DENIED',
  '15 LOCAL_AGENT_OBSERVATION_RESULT / OBSERVE / USER_LOCAL_AGENT / patch.apply / approval true / may mutate false / enabled true / status SUCCEEDED / fresh observation true / dry-run true / mutation applied false',
  '16 LOCAL_AGENT_APPROVAL_DECISION / REQUEST_APPROVAL / USER_LOCAL_AGENT / patch.apply / approval true / may mutate false / enabled true / status APPROVED_HELD / approval state APPROVED / recommended action CHECK_ENQUEUE_REFUSAL / label Check enqueue refusal / enabled true / method POST / endpoint /api/code-agent/loop/runner/enqueue-read-only / request creation false / push false / claim false / mutation false / reason Confirm the runner will not enqueue mutation work from this handoff state.',
  '17 LOCAL_AGENT_APPROVAL_REQUEST_CREATED / REQUEST_APPROVAL / USER_LOCAL_AGENT / patch.apply / approval true / may mutate false / enabled true / status APPROVAL_REQUIRED / approval state REQUIRED / validated dry-run intent true / dry-run intent persisted true / review surface CODE_WORKSPACE_LOOP_REVIEW / request persisted true / queue false / push false / claimable false / dry-run only true / mutation allowed false / dry-run intent review required true / recommended action WAIT_FOR_APPROVAL / label Wait for approval / enabled true / request creation false / push false / claim false / mutation false / reason Review the persisted validated dry-run intent before any future claimable non-mutating dry-run.',
  '18 STOP_OUTCOME_RECORDED / COMPLETE_OR_PAUSE / approval false / may mutate false / enabled true / status RECORDED / final result false / stop TOOL_FAILED / outcome REPORT_TOOL_FAILURE',
  '19 STOP_OUTCOME_RECORDED / COMPLETE_OR_PAUSE / approval false / may mutate false / enabled true / status RECORDED / final result false / stop APPROVAL_DENIED / outcome REPORT_APPROVAL_DENIED',
  '20 STOP_OUTCOME_RECORDED / COMPLETE_OR_PAUSE / approval false / may mutate false / enabled true / status RECORDED / final result false / stop AGENT_UNAVAILABLE / outcome WAIT_FOR_LOCAL_AGENT',
  '21 STOP_OUTCOME_RECORDED / COMPLETE_OR_PAUSE / approval false / may mutate false / enabled true / status RECORDED / final result false / stop TIMEOUT / outcome REPORT_TIMEOUT',
  '22 STOP_OUTCOME_RECORDED / COMPLETE_OR_PAUSE / approval false / may mutate false / enabled true / status RECORDED / final result false / stop CANCELLATION / outcome REPORT_CANCELLATION',
]);
assert.equal(buildAgentLoopTimelineHistoryView([]), null);
assert.equal(buildAgentLoopTimelineHistoryView(null), null);

console.log('agentLoopTimelineSummary view tests passed');
