export function buildCodeWorkspaceReadinessSmokeProps({
  requestId,
  latestAttempt,
  readinessOverrides = {},
  dryRunRequest = null,
  dryRunResult = null,
}) {
  const resolvedDryRunRequest = dryRunRequest || (dryRunResult ? { requestId: dryRunResult.requestId } : null);
  return {
    repositories: [],
    selectedRepositoryId: 'repo-1',
    codeAgentInstruction: 'test',
    codeAgentLoopPreview: {
      loopId: 'loop-preview-1',
      status: 'PREVIEW_ONLY',
      maxSteps: 6,
      timeoutSeconds: 120,
      mutationEnabled: false,
      timelinePersistenceEnabled: true,
      cancellationEnabled: false,
      steps: [
        {
          index: 1,
          phase: 'PLAN',
          action: 'Retrieve code evidence and form a bounded repair plan.',
          executionTarget: 'SERVER_LOCAL',
          requiresApproval: false,
          mayMutate: false,
          enabled: true,
          stopOnFailure: 'Stop and ask for clarification when evidence is weak or the target is ambiguous.',
        },
        {
          index: 3,
          phase: 'REQUEST_APPROVAL',
          action: 'Require explicit user approval before any side-effectful tool can run.',
          executionTarget: 'USER_LOCAL_AGENT',
          toolName: 'patch.apply',
          requiresApproval: true,
          mayMutate: false,
          enabled: true,
          stopOnFailure: 'Stop on approval denial, missing agent, disconnected agent, or unapproved workspace.',
        },
      ],
      stopConditions: [
        { key: 'MAX_STEPS', message: 'Stop when the bounded step count is reached.' },
        { key: 'MUTATION_DISABLED', message: 'Do not apply patches, run tests, restore rollback, update RAG freshness, or publish a mutation result in this preview slice.' },
      ],
      warnings: [
        'Agent loop preview is read-only and does not create, push, claim, release, or execute Local Agent mutation requests.',
      ],
    },
    codeAgentLoopTimelines: [
      {
        id: 'loop-preview-1',
        status: 'PREVIEW_ONLY',
        maxSteps: 6,
        timeoutSeconds: 120,
        mutationEnabled: false,
        timelinePersistenceEnabled: true,
        cancellationEnabled: false,
        instruction: 'test',
        createdAt: '2026-06-30T12:00:00Z',
        events: [
          {
            sequenceNumber: 1,
            eventType: 'LOOP_PREVIEW_CREATED',
            requiresApproval: false,
            mayMutate: false,
            enabled: false,
            details: {},
          },
          {
            sequenceNumber: 3,
            eventType: 'APPROVAL_CHECKPOINT_PREVIEW',
            phase: 'REQUEST_APPROVAL',
            executionTarget: 'USER_LOCAL_AGENT',
            toolName: 'patch.apply',
            requiresApproval: true,
            mayMutate: false,
            enabled: true,
            details: {
              action: 'Require explicit user approval before any side-effectful tool can run.',
            },
          },
          {
            sequenceNumber: 8,
            eventType: 'TIMEOUT_POLICY_REGISTERED',
            requiresApproval: false,
            mayMutate: false,
            enabled: false,
            details: {
              status: 'REGISTERED',
              timeoutSeconds: 120,
            },
          },
          {
            sequenceNumber: 9,
            eventType: 'CANCELLATION_POLICY_REGISTERED',
            requiresApproval: false,
            mayMutate: false,
            enabled: false,
            details: {
              status: 'DISABLED',
              cancellationEnabled: false,
            },
          },
          {
            sequenceNumber: 10,
            eventType: 'FINAL_RESULT_POLICY_REGISTERED',
            requiresApproval: false,
            mayMutate: false,
            enabled: false,
            details: {
              status: 'PENDING_PREVIEW_ONLY',
              finalResultEnabled: false,
            },
          },
          {
            sequenceNumber: 11,
            eventType: 'STOP_OUTCOME_POLICY_REGISTERED',
            requiresApproval: false,
            mayMutate: false,
            enabled: false,
            details: {
              status: 'REGISTERED',
              stopKey: 'WEAK_EVIDENCE',
              outcome: 'ASK_FOR_CLARIFICATION',
            },
          },
          {
            sequenceNumber: 12,
            eventType: 'STOP_OUTCOME_POLICY_REGISTERED',
            requiresApproval: false,
            mayMutate: false,
            enabled: false,
            details: {
              status: 'REGISTERED',
              stopKey: 'AGENT_UNAVAILABLE',
              outcome: 'WAIT_FOR_LOCAL_AGENT',
            },
          },
          {
            sequenceNumber: 13,
            eventType: 'STOP_OUTCOME_POLICY_REGISTERED',
            requiresApproval: false,
            mayMutate: false,
            enabled: false,
            details: {
              status: 'REGISTERED',
              stopKey: 'TOOL_FAILED',
              outcome: 'REPORT_TOOL_FAILURE',
            },
          },
          {
            sequenceNumber: 14,
            eventType: 'STOP_OUTCOME_POLICY_REGISTERED',
            requiresApproval: false,
            mayMutate: false,
            enabled: false,
            details: {
              status: 'REGISTERED',
              stopKey: 'APPROVAL_DENIED',
              outcome: 'REPORT_APPROVAL_DENIED',
            },
          },
          {
            sequenceNumber: 15,
            eventType: 'LOCAL_AGENT_OBSERVATION_RESULT',
            phase: 'OBSERVE',
            executionTarget: 'USER_LOCAL_AGENT',
            toolName: 'patch.apply',
            requiresApproval: true,
            mayMutate: false,
            enabled: true,
            details: {
              status: 'SUCCEEDED',
              freshObservationOnly: true,
              dryRun: true,
              mutationApplied: false,
            },
          },
          {
            sequenceNumber: 16,
            eventType: 'LOCAL_AGENT_APPROVAL_DECISION',
            phase: 'REQUEST_APPROVAL',
            executionTarget: 'USER_LOCAL_AGENT',
            toolName: 'patch.apply',
            requiresApproval: true,
            mayMutate: false,
            enabled: true,
            details: {
              status: 'APPROVED_HELD',
              approvalState: 'APPROVED',
            },
          },
        ],
      },
    ],
    codeAgentPatch: {
      summary: 'patch proposal',
      valid: true,
      files: [],
      warnings: [],
    },
    codeAgentLocalPatchRequest: {
      requestId,
      status: 'APPROVED_HELD',
      toolName: 'patch.apply',
      approvalState: 'APPROVED',
      input: {
        loopId: 'loop-preview-1',
        sourceRepository: {},
      },
    },
    codeAgentLocalPatchDryRunRequest: resolvedDryRunRequest,
    codeAgentLocalPatchDryRunResult: dryRunResult,
    codeAgentLocalPatchReadiness: {
      requestId,
      readyToRelease: false,
      message: 'Held patch request is not ready for Local Agent execution.',
      patchExecutionGate: {
        status: 'BLOCKED_RELEASE_DISABLED',
        claimEnabled: false,
        releaseGateEnabled: false,
        message: 'Patch execution remains disabled.',
      },
      releaseAttemptModel: {
        status: 'READY_RELEASE_ATTEMPT_DISABLED',
        latestAttempt,
      },
      ...readinessOverrides,
    },
  };
}
