import assert from 'node:assert/strict';
import { buildMutationResultAggregationGateView } from './mutationResultAggregationGate.js';

const view = buildMutationResultAggregationGateView({
  schema: 'learnbot.local-agent.mutation-result-aggregation-gate.v1',
  status: 'REFUSED_RESULT_AGGREGATION_DISABLED',
  ragFreshnessReady: true,
  prerequisitesPassed: true,
  executionTarget: 'USER_LOCAL_AGENT',
  resultAggregationPolicy: 'DISABLED_AUDIT_ONLY',
  sourceRagFreshnessGateStatus: 'REFUSED_RAG_FRESHNESS_DISABLED',
  sourceRagFreshnessGatePublicationGateSchema: 'learnbot.local-agent.mutation-publication-gate.v1',
  sourceRagFreshnessGatePublicationGateStatus: 'REFUSED_PUBLICATION_DISABLED',
  sourceRagFreshnessGatePublicationGateSessionId: 'session-1',
  sourceRagFreshnessGatePublicationGateUserId: 'user-1',
  sourceRagFreshnessGatePublicationGateAgentId: 'agent-1',
  sourceRagFreshnessGatePublicationGateWorkspaceId: 'workspace-1',
  sourceRagFreshnessGateAcceptedObservationSummaryStatus: 'OBSERVED',
  sourceRagFreshnessGateAcceptedObservationCount: 2,
  sourceRagFreshnessGateAcceptedObservationAcceptedCount: 2,
  sourceRagFreshnessGateAcceptedObservationRejectedCount: 0,
  sourceRagFreshnessGateMissingMutationResultRiskVisible: false,
  sourceRagFreshnessGateStaleIndexRiskVisible: true,
  sourceRagFreshnessGateLatestAcceptedObservationStatus: 'ACCEPTED',
  sourceRagFreshnessGateLatestAcceptedObservationToolName: 'patch.apply',
  sourceRagFreshnessGateLatestAcceptedObservationVerificationStatus: 'PASSED',
  sourceRagFreshnessGateRollbackAcceptedObservationSummaryStatus: 'OBSERVED',
  sourceRagFreshnessGateRollbackAcceptedObservationSummaryObservationCount: 2,
  sourceRagFreshnessGateRollbackAcceptedObservationSummaryAcceptedCount: 2,
  sourceRagFreshnessGateRollbackAcceptedObservationSummaryRejectedCount: 0,
  sourceRagFreshnessGateRollbackAcceptedObservationSummaryMissingMutationResultRiskVisible: false,
  sourceRagFreshnessGateRollbackAcceptedObservationSummaryStaleIndexRiskVisible: true,
  sourceRequestId: 'request-123',
  releaseAttemptId: 'attempt-1234567890',
  sessionId: 'session-1',
  userId: 'user-1',
  agentId: 'agent-1',
  workspaceId: 'workspace-1',
  expectedResultCount: 4,
  completedResultCount: 0,
  acceptedResultCount: 0,
  rejectedResultCount: 0,
  intakePersistedResultCount: 0,
  mutationResultAggregationEnabled: false,
  resultAggregationInvocationEnabled: false,
  publicationEnabled: false,
  finalAnswerGenerationEnabled: false,
  finalAnswerCompletionEnabled: false,
  finalAnswerDeliveryEnabled: false,
  finalResponseHandoffEnabled: false,
  deliveryReceiptEnabled: false,
  acknowledgementSaveEnabled: false,
  ragFreshnessUpdateEnabled: false,
  rollbackFallbackExecutionEnabled: false,
  intakePersistenceEnabled: false,
  acceptedObservationPersistenceEnabled: false,
  postExecutionObservationEnabled: false,
  completedResultPersistenceEnabled: false,
  observationAcceptanceEnabled: false,
  releaseGateEnabled: false,
  requestCreationEnabled: false,
  pushEnabled: false,
  claimEnabled: false,
  executionEnabled: false,
  writeHelperEnabled: false,
  claimable: false,
  mutationAllowed: false,
  applyEnabled: false,
  testEnabled: false,
  rollbackRestoreEnabled: false,
  policyChecks: [
    {
      key: 'mutationRagFreshnessGate',
      status: 'REFUSED_RAG_FRESHNESS_DISABLED',
      passed: true,
      blocking: false,
      requestCreationEnabled: false,
      pushEnabled: false,
      claimEnabled: false,
      executionEnabled: false,
      writeHelperEnabled: false,
      claimable: false,
      mutationAllowed: false,
      mutationResultAggregationEnabled: false,
      publicationEnabled: false,
      finalAnswerGenerationEnabled: false,
      finalAnswerCompletionEnabled: false,
      finalAnswerDeliveryEnabled: false,
      finalResponseHandoffEnabled: false,
      deliveryReceiptEnabled: false,
      acknowledgementSaveEnabled: false,
      message: 'A disabled RAG freshness gate must refuse freshness updates before result aggregation can be considered.',
    },
    {
      key: 'resultAggregationPolicy',
      status: 'DISABLED',
      passed: false,
      blocking: true,
      requestCreationEnabled: false,
      pushEnabled: false,
      claimEnabled: false,
      executionEnabled: false,
      writeHelperEnabled: false,
      claimable: false,
      mutationAllowed: false,
      mutationResultAggregationEnabled: false,
      publicationEnabled: false,
      finalAnswerGenerationEnabled: false,
      finalAnswerCompletionEnabled: false,
      finalAnswerDeliveryEnabled: false,
      finalResponseHandoffEnabled: false,
      deliveryReceiptEnabled: false,
      acknowledgementSaveEnabled: false,
      message: 'Mutation result aggregation is disabled.',
    },
    {
      key: 'resultAggregation',
      status: 'DISABLED',
      passed: false,
      blocking: true,
      requestCreationEnabled: false,
      pushEnabled: false,
      claimEnabled: false,
      executionEnabled: false,
      writeHelperEnabled: false,
      claimable: false,
      mutationAllowed: false,
      mutationResultAggregationEnabled: false,
      publicationEnabled: false,
      finalAnswerGenerationEnabled: false,
      finalAnswerCompletionEnabled: false,
      finalAnswerDeliveryEnabled: false,
      finalResponseHandoffEnabled: false,
      deliveryReceiptEnabled: false,
      acknowledgementSaveEnabled: false,
      message: 'No mutation result aggregation may run while aggregation is disabled.',
    },
    {
      key: 'publication',
      status: 'DISABLED',
      passed: false,
      blocking: true,
      requestCreationEnabled: false,
      pushEnabled: false,
      claimEnabled: false,
      executionEnabled: false,
      writeHelperEnabled: false,
      claimable: false,
      mutationAllowed: false,
      mutationResultAggregationEnabled: false,
      publicationEnabled: false,
      finalAnswerGenerationEnabled: false,
      finalAnswerCompletionEnabled: false,
      finalAnswerDeliveryEnabled: false,
      finalResponseHandoffEnabled: false,
      deliveryReceiptEnabled: false,
      acknowledgementSaveEnabled: false,
      message: 'Final answer publication remains disabled until aggregation state is modeled.',
    },
    {
      key: 'finalAnswerGeneration',
      status: 'DISABLED',
      passed: false,
      blocking: true,
      requestCreationEnabled: false,
      pushEnabled: false,
      claimEnabled: false,
      executionEnabled: false,
      writeHelperEnabled: false,
      claimable: false,
      mutationAllowed: false,
      mutationResultAggregationEnabled: false,
      publicationEnabled: false,
      finalAnswerGenerationEnabled: false,
      finalAnswerCompletionEnabled: false,
      finalAnswerDeliveryEnabled: false,
      finalResponseHandoffEnabled: false,
      deliveryReceiptEnabled: false,
      acknowledgementSaveEnabled: false,
      message: 'Final-answer generation remains disabled until aggregation state is modeled.',
    },
  ],
  blockingKeys: [
    'resultAggregationPolicy',
    'resultAggregation',
    'publication',
    'finalAnswerGeneration',
    'mutationResultAggregationEnabled',
    'publicationEnabled',
    'finalAnswerGenerationEnabled',
    'finalAnswerCompletionEnabled',
    'finalAnswerDeliveryEnabled',
    'finalResponseHandoffEnabled',
    'deliveryReceiptEnabled',
    'acknowledgementSaveEnabled',
    'mutationAllowed',
  ],
  message: 'Local Agent mutation result aggregation is explicitly refused: no aggregation, publication, or final answer is enabled.',
});

assert.equal(view.show, true);
assert.equal(
  view.headerText,
  'mutation result aggregation gate: REFUSED_RESULT_AGGREGATION_DISABLED / learnbot.local-agent.mutation-result-aggregation-gate.v1 / RAG freshness ready true / prerequisites true / USER_LOCAL_AGENT / policy DISABLED_AUDIT_ONLY / RAG freshness status REFUSED_RAG_FRESHNESS_DISABLED'
);
assert.equal(
  view.idsText,
  'mutation result aggregation ids: source request-123 / release attempt- / session session-1 / user user-1 / agent agent-1 / workspace workspace-1'
);
assert.equal(
  view.countsText,
  'mutation result aggregation counts: expected 4 / completed 0 / accepted 0 / rejected 0 / intake persisted 0'
);
assert.equal(
  view.sourceContextText,
  'mutation result aggregation source context: publication gate REFUSED_PUBLICATION_DISABLED / publication schema learnbot.local-agent.mutation-publication-gate.v1 / publication session session-1 / publication user user-1 / publication agent agent-1 / publication workspace workspace-1 / RAG observations OBSERVED / count 2 / accepted 2 / rejected 0 / missing result risk false / stale index risk true / latest ACCEPTED / tool patch.apply / verification PASSED / rollback summary observations OBSERVED / rollback summary count 2 / rollback summary accepted 2 / rollback summary rejected 0 / rollback summary missing result risk false / rollback summary stale index risk true'
);
assert.equal(
  view.disabledText,
  'mutation result aggregation disabled: result aggregation false / aggregation invocation false / publication false / final answer false / final-answer completion false / final-answer delivery false / final-response handoff false / delivery receipt false / acknowledgement save false / rag freshness false / rollback fallback false / intake persistence false / accepted observation persistence false / post-execution observation false / result persistence false / acceptance false / release gate false / request creation false / push false / claim false / execution false / write helper false / claimable false / mutation false / apply false / test false / rollback restore false'
);
assert.deepEqual(view.policyLines, [
  'result aggregation policy mutationRagFreshnessGate: REFUSED_RAG_FRESHNESS_DISABLED / passed true / blocking false / request creation false / push false / claim false / execution false / write helper false / claimable false / mutation false / result aggregation false / publication false / final answer false / final-answer completion false / final-answer delivery false / final-response handoff false / delivery receipt false / acknowledgement save false / A disabled RAG freshness gate must refuse freshness updates before result aggregation can be considered.',
  'result aggregation policy resultAggregationPolicy: DISABLED / passed false / blocking true / request creation false / push false / claim false / execution false / write helper false / claimable false / mutation false / result aggregation false / publication false / final answer false / final-answer completion false / final-answer delivery false / final-response handoff false / delivery receipt false / acknowledgement save false / Mutation result aggregation is disabled.',
  'result aggregation policy resultAggregation: DISABLED / passed false / blocking true / request creation false / push false / claim false / execution false / write helper false / claimable false / mutation false / result aggregation false / publication false / final answer false / final-answer completion false / final-answer delivery false / final-response handoff false / delivery receipt false / acknowledgement save false / No mutation result aggregation may run while aggregation is disabled.',
  'result aggregation policy publication: DISABLED / passed false / blocking true / request creation false / push false / claim false / execution false / write helper false / claimable false / mutation false / result aggregation false / publication false / final answer false / final-answer completion false / final-answer delivery false / final-response handoff false / delivery receipt false / acknowledgement save false / Final answer publication remains disabled until aggregation state is modeled.',
  'result aggregation policy finalAnswerGeneration: DISABLED / passed false / blocking true / request creation false / push false / claim false / execution false / write helper false / claimable false / mutation false / result aggregation false / publication false / final answer false / final-answer completion false / final-answer delivery false / final-response handoff false / delivery receipt false / acknowledgement save false / Final-answer generation remains disabled until aggregation state is modeled.',
]);
assert.equal(
  view.blockingText,
  'mutation result aggregation blocking keys: resultAggregationPolicy, resultAggregation, publication, finalAnswerGeneration, mutationResultAggregationEnabled, publicationEnabled, finalAnswerGenerationEnabled, finalAnswerCompletionEnabled, finalAnswerDeliveryEnabled, finalResponseHandoffEnabled, deliveryReceiptEnabled, acknowledgementSaveEnabled, mutationAllowed'
);
assert.match(view.message, /explicitly refused/);

const blocked = buildMutationResultAggregationGateView({
  status: 'BLOCKED_RESULT_AGGREGATION_DISABLED',
  expectedResultCount: 0,
  intakePersistedResultCount: 0,
  policyChecks: [
    {
      key: 'unknownPolicy',
    },
  ],
});

assert.equal(blocked.headerText, 'mutation result aggregation gate: BLOCKED_RESULT_AGGREGATION_DISABLED');
assert.equal(blocked.countsText, 'mutation result aggregation counts: expected 0 / intake persisted 0');
assert.deepEqual(blocked.policyLines, [
  'result aggregation policy unknownPolicy: UNKNOWN',
]);

const hidden = buildMutationResultAggregationGateView(null);
assert.equal(hidden.show, false);
assert.deepEqual(hidden.policyLines, []);
