import assert from 'node:assert/strict';
import { buildMutationFinalAnswerDeliveryGateView } from './mutationFinalAnswerDeliveryGate.js';

const view = buildMutationFinalAnswerDeliveryGateView({
  schema: 'learnbot.local-agent.mutation-final-answer-delivery-gate.v1',
  status: 'REFUSED_FINAL_ANSWER_DELIVERY_DISABLED',
  finalResponseHandoffReady: true,
  prerequisitesPassed: true,
  executionTarget: 'USER_LOCAL_AGENT',
  finalAnswerDeliveryPolicy: 'DISABLED_AUDIT_ONLY',
  deliveryHandoffEnabled: false,
  deliveryReceiptEnabled: false,
  acknowledgementSaveEnabled: false,
  sourceFinalResponseHandoffGateStatus: 'REFUSED_FINAL_RESPONSE_HANDOFF_DISABLED',
  sourceFinalResponseHandoffGateSchema: 'learnbot.local-agent.mutation-final-response-handoff-gate.v1',
  sourceFinalResponseHandoffGatePublicationGateStatus: 'REFUSED_PUBLICATION_DISABLED',
  sourceFinalResponseHandoffGatePublicationGateSchema: 'learnbot.local-agent.mutation-publication-gate.v1',
  sourceFinalResponseHandoffGatePublicationGateSessionId: 'session-1',
  sourceFinalResponseHandoffGatePublicationGateUserId: 'user-1',
  sourceFinalResponseHandoffGatePublicationGateAgentId: 'agent-1',
  sourceFinalResponseHandoffGatePublicationGateWorkspaceId: 'workspace-1',
  sourceFinalResponseHandoffGatePublicationBoundaryStatus: 'READY_PUBLICATION_DISABLED',
  sourceFinalResponseHandoffGatePublicationBoundaryPrerequisitesPassed: true,
  sourceFinalResponseHandoffGatePublicationBoundaryDraftStatus: 'READY_DRAFT_DISABLED',
  sourceFinalResponseHandoffGatePublicationBoundaryDraftSections: ['changedFiles', 'verificationOutcome', 'rollbackState', 'ragFreshnessState'],
  sourceFinalResponseHandoffGateAcceptedObservationSummaryStatus: 'OBSERVED',
  sourceFinalResponseHandoffGateAcceptedObservationCount: 2,
  sourceFinalResponseHandoffGateAcceptedObservationAcceptedCount: 2,
  sourceFinalResponseHandoffGateAcceptedObservationRejectedCount: 0,
  sourceFinalResponseHandoffGateMissingMutationResultRiskVisible: false,
  sourceFinalResponseHandoffGateStaleIndexRiskVisible: true,
  sourceFinalResponseHandoffGatePublicationAcceptedObservationSummaryStatus: 'OBSERVED',
  sourceFinalResponseHandoffGatePublicationAcceptedObservationCount: 2,
  sourceFinalResponseHandoffGatePublicationAcceptedObservationAcceptedCount: 2,
  sourceFinalResponseHandoffGatePublicationAcceptedObservationRejectedCount: 0,
  sourceFinalResponseHandoffGatePublicationMissingMutationResultRiskVisible: false,
  sourceFinalResponseHandoffGatePublicationStaleIndexRiskVisible: true,
  sourceFinalResponseHandoffGatePublicationLatestAcceptedObservationStatus: 'ACCEPTED',
  sourceFinalResponseHandoffGatePublicationLatestAcceptedObservationToolName: 'patch.apply',
  sourceFinalResponseHandoffGatePublicationLatestAcceptedObservationVerificationStatus: 'PASSED',
  sourceFinalResponseHandoffGatePublicationRollbackAcceptedObservationSummaryStatus: 'OBSERVED',
  sourceFinalResponseHandoffGatePublicationRollbackAcceptedObservationSummaryObservationCount: 2,
  sourceFinalResponseHandoffGatePublicationRollbackAcceptedObservationSummaryAcceptedCount: 2,
  sourceFinalResponseHandoffGatePublicationRollbackAcceptedObservationSummaryRejectedCount: 0,
  sourceFinalResponseHandoffGatePublicationRollbackAcceptedObservationSummaryMissingMutationResultRiskVisible: false,
  sourceFinalResponseHandoffGatePublicationRollbackAcceptedObservationSummaryStaleIndexRiskVisible: true,
  sourceRequestId: 'request-123',
  releaseAttemptId: 'attempt-1234567890',
  sessionId: 'session-1',
  userId: 'user-1',
  agentId: 'agent-1',
  workspaceId: 'workspace-1',
  expectedResultCount: 4,
  completedResultCount: 0,
  acceptedResultCount: 0,
  rejectedResultCount: 0,
  intakePersistedResultCount: 0,
  finalAnswerDeliveryEnabled: false,
  finalResponseHandoffEnabled: false,
  userVisibleCompletionEnabled: false,
  conversationTurnSaveEnabled: false,
  finalAnswerPersistenceEnabled: false,
  finalAnswerCompletionEnabled: false,
  finalAnswerGenerationEnabled: false,
  publicationEnabled: false,
  mutationResultAggregationEnabled: false,
  ragFreshnessUpdateEnabled: false,
  rollbackFallbackExecutionEnabled: false,
  intakePersistenceEnabled: false,
  acceptedObservationPersistenceEnabled: false,
  postExecutionObservationEnabled: false,
  completedResultPersistenceEnabled: false,
  observationAcceptanceEnabled: false,
  releaseGateEnabled: false,
  requestCreationEnabled: false,
  pushEnabled: false,
  claimEnabled: false,
  executionEnabled: false,
  writeHelperEnabled: false,
  claimable: false,
  mutationAllowed: false,
  applyEnabled: false,
  testEnabled: false,
  rollbackRestoreEnabled: false,
  policyChecks: [
    {
      key: 'mutationFinalResponseHandoffGate',
      status: 'REFUSED_FINAL_RESPONSE_HANDOFF_DISABLED',
      passed: true,
      blocking: false,
      requestCreationEnabled: false,
      pushEnabled: false,
      claimEnabled: false,
      executionEnabled: false,
      writeHelperEnabled: false,
      claimable: false,
      mutationAllowed: false,
      publicationEnabled: false,
      finalAnswerGenerationEnabled: false,
      finalAnswerCompletionEnabled: false,
      finalAnswerDeliveryEnabled: false,
      deliveryReceiptEnabled: false,
      acknowledgementSaveEnabled: false,
      finalAnswerPersistenceEnabled: false,
      conversationTurnSaveEnabled: false,
      userVisibleCompletionEnabled: false,
      finalResponseHandoffEnabled: false,
      deliveryHandoffEnabled: false,
      message: 'A disabled final-response handoff gate must refuse handoff before final-answer delivery can be considered.',
    },
    {
      key: 'finalAnswerDeliveryPolicy',
      status: 'DISABLED',
      passed: false,
      blocking: true,
      requestCreationEnabled: false,
      pushEnabled: false,
      claimEnabled: false,
      executionEnabled: false,
      writeHelperEnabled: false,
      claimable: false,
      mutationAllowed: false,
      publicationEnabled: false,
      finalAnswerGenerationEnabled: false,
      finalAnswerCompletionEnabled: false,
      finalAnswerDeliveryEnabled: false,
      deliveryReceiptEnabled: false,
      acknowledgementSaveEnabled: false,
      finalAnswerPersistenceEnabled: false,
      conversationTurnSaveEnabled: false,
      userVisibleCompletionEnabled: false,
      finalResponseHandoffEnabled: false,
      deliveryHandoffEnabled: false,
      message: 'Mutation final-answer delivery and delivery handoff are disabled.',
    },
    {
      key: 'finalAnswerDelivery',
      status: 'DISABLED',
      passed: false,
      blocking: true,
      requestCreationEnabled: false,
      pushEnabled: false,
      claimEnabled: false,
      executionEnabled: false,
      writeHelperEnabled: false,
      claimable: false,
      mutationAllowed: false,
      publicationEnabled: false,
      finalAnswerGenerationEnabled: false,
      finalAnswerCompletionEnabled: false,
      finalAnswerDeliveryEnabled: false,
      deliveryReceiptEnabled: false,
      acknowledgementSaveEnabled: false,
      finalAnswerPersistenceEnabled: false,
      conversationTurnSaveEnabled: false,
      userVisibleCompletionEnabled: false,
      finalResponseHandoffEnabled: false,
      deliveryHandoffEnabled: false,
      message: 'No final answer may be delivered while final-answer delivery is disabled.',
    },
    {
      key: 'deliveryHandoff',
      status: 'DISABLED',
      passed: false,
      blocking: true,
      requestCreationEnabled: false,
      pushEnabled: false,
      claimEnabled: false,
      executionEnabled: false,
      writeHelperEnabled: false,
      claimable: false,
      mutationAllowed: false,
      publicationEnabled: false,
      finalAnswerGenerationEnabled: false,
      finalAnswerCompletionEnabled: false,
      finalAnswerDeliveryEnabled: false,
      deliveryReceiptEnabled: false,
      acknowledgementSaveEnabled: false,
      finalAnswerPersistenceEnabled: false,
      conversationTurnSaveEnabled: false,
      userVisibleCompletionEnabled: false,
      finalResponseHandoffEnabled: false,
      deliveryHandoffEnabled: false,
      message: 'No delivery handoff may run while final-answer delivery is disabled.',
    },
    {
      key: 'finalResponseHandoff',
      status: 'DISABLED',
      passed: false,
      blocking: true,
      requestCreationEnabled: false,
      pushEnabled: false,
      claimEnabled: false,
      executionEnabled: false,
      writeHelperEnabled: false,
      claimable: false,
      mutationAllowed: false,
      publicationEnabled: false,
      finalAnswerGenerationEnabled: false,
      finalAnswerCompletionEnabled: false,
      finalAnswerDeliveryEnabled: false,
      deliveryReceiptEnabled: false,
      acknowledgementSaveEnabled: false,
      finalAnswerPersistenceEnabled: false,
      conversationTurnSaveEnabled: false,
      userVisibleCompletionEnabled: false,
      finalResponseHandoffEnabled: false,
      deliveryHandoffEnabled: false,
      message: 'No final response may be handed off while final-answer delivery is disabled.',
    },
  ],
  blockingKeys: [
    'finalAnswerDeliveryPolicy',
    'finalAnswerDelivery',
    'deliveryHandoff',
    'finalResponseHandoff',
    'finalAnswerDeliveryEnabled',
    'deliveryHandoffEnabled',
    'deliveryReceiptEnabled',
    'acknowledgementSaveEnabled',
    'finalResponseHandoffEnabled',
    'userVisibleCompletionEnabled',
    'conversationTurnSaveEnabled',
    'finalAnswerPersistenceEnabled',
    'finalAnswerCompletionEnabled',
    'finalAnswerGenerationEnabled',
    'mutationAllowed',
  ],
  message: 'Local Agent mutation final-answer delivery is explicitly refused: no final answer is delivered and no delivery handoff runs.',
});

assert.equal(view.show, true);
assert.equal(
  view.headerText,
  'mutation final-answer delivery gate: REFUSED_FINAL_ANSWER_DELIVERY_DISABLED / learnbot.local-agent.mutation-final-answer-delivery-gate.v1 / final response handoff ready true / prerequisites true / USER_LOCAL_AGENT / policy DISABLED_AUDIT_ONLY / delivery handoff false / final-response handoff status REFUSED_FINAL_RESPONSE_HANDOFF_DISABLED / learnbot.local-agent.mutation-final-response-handoff-gate.v1'
);
assert.equal(
  view.idsText,
  'mutation final-answer delivery ids: source request-123 / release attempt- / session session-1 / user user-1 / agent agent-1 / workspace workspace-1'
);
assert.equal(
  view.countsText,
  'mutation final-answer delivery counts: expected 4 / completed 0 / accepted 0 / rejected 0 / intake persisted 0'
);
assert.equal(
  view.sourceContextText,
  'mutation final-answer delivery source context: publication gate REFUSED_PUBLICATION_DISABLED / publication schema learnbot.local-agent.mutation-publication-gate.v1 / publication session session-1 / publication user user-1 / publication agent agent-1 / publication workspace workspace-1 / publication boundary READY_PUBLICATION_DISABLED / publication prerequisites true / draft READY_DRAFT_DISABLED / sections changedFiles, verificationOutcome, rollbackState, ragFreshnessState / observations OBSERVED / observed 2 / accepted 2 / rejected 0 / missing result risk false / stale index risk true / publication observations OBSERVED / publication count 2 / publication accepted 2 / publication rejected 0 / publication missing result risk false / publication stale index risk true / publication latest ACCEPTED / publication tool patch.apply / publication verification PASSED / publication rollback summary observations OBSERVED / publication rollback summary count 2 / publication rollback summary accepted 2 / publication rollback summary rejected 0 / publication rollback summary missing result risk false / publication rollback summary stale index risk true'
);
assert.equal(
  view.disabledText,
  'mutation final-answer delivery disabled: delivery false / delivery handoff false / delivery receipt false / acknowledgement save false / final response handoff false / user-visible completion false / conversation save false / persistence false / completion false / final answer false / publication false / result aggregation false / rag freshness false / rollback fallback false / intake persistence false / accepted observation persistence false / post-execution observation false / result persistence false / acceptance false / release gate false / request creation false / push false / claim false / execution false / write helper false / claimable false / mutation false / apply false / test false / rollback restore false'
);
assert.deepEqual(view.policyLines, [
  'final-answer delivery policy mutationFinalResponseHandoffGate: REFUSED_FINAL_RESPONSE_HANDOFF_DISABLED / passed true / blocking false / request creation false / push false / claim false / execution false / write helper false / claimable false / mutation false / publication false / final answer false / completion false / delivery false / delivery receipt false / acknowledgement save false / persistence false / conversation save false / user-visible completion false / final response handoff false / delivery handoff false / A disabled final-response handoff gate must refuse handoff before final-answer delivery can be considered.',
  'final-answer delivery policy finalAnswerDeliveryPolicy: DISABLED / passed false / blocking true / request creation false / push false / claim false / execution false / write helper false / claimable false / mutation false / publication false / final answer false / completion false / delivery false / delivery receipt false / acknowledgement save false / persistence false / conversation save false / user-visible completion false / final response handoff false / delivery handoff false / Mutation final-answer delivery and delivery handoff are disabled.',
  'final-answer delivery policy finalAnswerDelivery: DISABLED / passed false / blocking true / request creation false / push false / claim false / execution false / write helper false / claimable false / mutation false / publication false / final answer false / completion false / delivery false / delivery receipt false / acknowledgement save false / persistence false / conversation save false / user-visible completion false / final response handoff false / delivery handoff false / No final answer may be delivered while final-answer delivery is disabled.',
  'final-answer delivery policy deliveryHandoff: DISABLED / passed false / blocking true / request creation false / push false / claim false / execution false / write helper false / claimable false / mutation false / publication false / final answer false / completion false / delivery false / delivery receipt false / acknowledgement save false / persistence false / conversation save false / user-visible completion false / final response handoff false / delivery handoff false / No delivery handoff may run while final-answer delivery is disabled.',
  'final-answer delivery policy finalResponseHandoff: DISABLED / passed false / blocking true / request creation false / push false / claim false / execution false / write helper false / claimable false / mutation false / publication false / final answer false / completion false / delivery false / delivery receipt false / acknowledgement save false / persistence false / conversation save false / user-visible completion false / final response handoff false / delivery handoff false / No final response may be handed off while final-answer delivery is disabled.',
]);
assert.equal(
  view.blockingText,
  'mutation final-answer delivery blocking keys: finalAnswerDeliveryPolicy, finalAnswerDelivery, deliveryHandoff, finalResponseHandoff, finalAnswerDeliveryEnabled, deliveryHandoffEnabled, deliveryReceiptEnabled, acknowledgementSaveEnabled, finalResponseHandoffEnabled, userVisibleCompletionEnabled, conversationTurnSaveEnabled, finalAnswerPersistenceEnabled, finalAnswerCompletionEnabled, finalAnswerGenerationEnabled, mutationAllowed'
);
assert.match(view.message, /explicitly refused/);

const hidden = buildMutationFinalAnswerDeliveryGateView(null);
assert.equal(hidden.show, false);
assert.deepEqual(hidden.policyLines, []);

const blocked = buildMutationFinalAnswerDeliveryGateView({
  policyChecks: null,
  blockingKeys: null,
  message: 'Local Agent mutation final-answer delivery is blocked because the disabled final-response handoff gate is incomplete.',
});
assert.equal(blocked.show, true);
assert.equal(
  blocked.headerText,
  'mutation final-answer delivery gate: BLOCKED_FINAL_ANSWER_DELIVERY_DISABLED'
);
assert.deepEqual(blocked.policyLines, []);
assert.equal(blocked.blockingText, '');
assert.match(blocked.message, /blocked/);
