import assert from 'node:assert/strict';
import { buildMutationCompletionSummaryView } from './mutationCompletionSummary.js';

const view = buildMutationCompletionSummaryView({
  schema: 'learnbot.local-agent.mutation-completion-summary.v1',
  status: 'READY_COMPLETION_DISABLED',
  prerequisitesPassed: true,
  executionTarget: 'USER_LOCAL_AGENT',
  sourceFinalAnswerDeliveryReceiptGateStatus: 'REFUSED_FINAL_ANSWER_DELIVERY_RECEIPT_DISABLED',
  sourceFinalAnswerDeliveryReceiptGateAcknowledgementSavePolicy: 'DISABLED_AUDIT_ONLY',
  sourceFinalAnswerDeliveryReceiptGateAcknowledgementSaveEnabled: false,
  sourceFinalAnswerDeliveryReceiptGatePublicationGateStatus: 'REFUSED_PUBLICATION_DISABLED',
  sourceFinalAnswerDeliveryReceiptGatePublicationGateSchema: 'learnbot.local-agent.mutation-publication-gate.v1',
  sourceFinalAnswerDeliveryReceiptGatePublicationGateSessionId: 'session-1',
  sourceFinalAnswerDeliveryReceiptGatePublicationGateUserId: 'user-1',
  sourceFinalAnswerDeliveryReceiptGatePublicationGateAgentId: 'agent-1',
  sourceFinalAnswerDeliveryReceiptGatePublicationGateWorkspaceId: 'workspace-1',
  sourceFinalAnswerDeliveryReceiptGatePublicationBoundaryStatus: 'READY_PUBLICATION_DISABLED',
  sourceFinalAnswerDeliveryReceiptGatePublicationBoundaryDraftStatus: 'READY_DRAFT_DISABLED',
  sourceFinalAnswerDeliveryReceiptGateAcceptedObservationCount: 2,
  sourceFinalAnswerDeliveryReceiptGateAcceptedObservationAcceptedCount: 2,
  sourceFinalAnswerDeliveryReceiptGateAcceptedObservationRejectedCount: 0,
  sourceFinalAnswerDeliveryReceiptGateMissingMutationResultRiskVisible: false,
  sourceFinalAnswerDeliveryReceiptGateStaleIndexRiskVisible: true,
  sourceFinalAnswerDeliveryReceiptGatePublicationAcceptedObservationSummaryStatus: 'OBSERVED',
  sourceFinalAnswerDeliveryReceiptGatePublicationAcceptedObservationCount: 2,
  sourceFinalAnswerDeliveryReceiptGatePublicationAcceptedObservationAcceptedCount: 2,
  sourceFinalAnswerDeliveryReceiptGatePublicationAcceptedObservationRejectedCount: 0,
  sourceFinalAnswerDeliveryReceiptGatePublicationMissingMutationResultRiskVisible: false,
  sourceFinalAnswerDeliveryReceiptGatePublicationStaleIndexRiskVisible: true,
  sourceFinalAnswerDeliveryReceiptGatePublicationLatestAcceptedObservationStatus: 'ACCEPTED',
  sourceFinalAnswerDeliveryReceiptGatePublicationLatestAcceptedObservationToolName: 'patch.apply',
  sourceFinalAnswerDeliveryReceiptGatePublicationLatestAcceptedObservationVerificationStatus: 'PASSED',
  sourceFinalAnswerDeliveryReceiptGatePublicationRollbackAcceptedObservationSummaryStatus: 'OBSERVED',
  sourceFinalAnswerDeliveryReceiptGatePublicationRollbackAcceptedObservationSummaryObservationCount: 2,
  sourceFinalAnswerDeliveryReceiptGatePublicationRollbackAcceptedObservationSummaryAcceptedCount: 2,
  sourceFinalAnswerDeliveryReceiptGatePublicationRollbackAcceptedObservationSummaryRejectedCount: 0,
  sourceFinalAnswerDeliveryReceiptGatePublicationRollbackAcceptedObservationSummaryMissingMutationResultRiskVisible: false,
  sourceFinalAnswerDeliveryReceiptGatePublicationRollbackAcceptedObservationSummaryStaleIndexRiskVisible: true,
  releaseGateEnabled: false,
  requestCreationEnabled: false,
  pushEnabled: false,
  claimEnabled: false,
  writeHelperEnabled: false,
  claimable: false,
  mutationAllowed: false,
  applyEnabled: false,
  testEnabled: false,
  rollbackRestoreEnabled: false,
  ragFreshnessUpdateEnabled: false,
  mutationResultAggregationEnabled: false,
  publicationEnabled: false,
  finalAnswerGenerationEnabled: false,
  finalAnswerCompletionEnabled: false,
  finalAnswerDeliveryEnabled: false,
  finalAnswerPersistenceEnabled: false,
  conversationTurnSaveEnabled: false,
  userVisibleCompletionEnabled: false,
  finalResponseHandoffEnabled: false,
  deliveryHandoffEnabled: false,
  deliveryReceiptEnabled: false,
  acknowledgementSaveEnabled: false,
  items: [
    {
      key: 'releaseAttemptReadiness',
      status: 'READY',
      passed: true,
      blocking: false,
      releaseGateEnabled: false,
      requestCreationEnabled: false,
      pushEnabled: false,
      claimable: false,
      mutationAllowed: false,
      mutationResultAggregationEnabled: false,
      publicationEnabled: false,
      finalAnswerGenerationEnabled: false,
      finalAnswerCompletionEnabled: false,
      finalAnswerDeliveryEnabled: false,
      finalAnswerPersistenceEnabled: false,
      conversationTurnSaveEnabled: false,
      userVisibleCompletionEnabled: false,
      finalResponseHandoffEnabled: false,
      deliveryHandoffEnabled: false,
      deliveryReceiptEnabled: false,
      acknowledgementSaveEnabled: false,
      message: 'Latest release attempt must be fresh, complete, and based on passing patch preconditions.',
    },
    {
      key: 'mutationFinalAnswerDeliveryGate',
      status: 'REFUSED_FINAL_ANSWER_DELIVERY_DISABLED',
      passed: true,
      blocking: false,
      releaseGateEnabled: false,
      requestCreationEnabled: false,
      pushEnabled: false,
      claimable: false,
      mutationAllowed: false,
      mutationResultAggregationEnabled: false,
      publicationEnabled: false,
      finalAnswerGenerationEnabled: false,
      finalAnswerCompletionEnabled: false,
      finalAnswerDeliveryEnabled: false,
      finalAnswerPersistenceEnabled: false,
      conversationTurnSaveEnabled: false,
      userVisibleCompletionEnabled: false,
      finalResponseHandoffEnabled: false,
      deliveryHandoffEnabled: false,
      deliveryReceiptEnabled: false,
      acknowledgementSaveEnabled: false,
      message: 'Future mutation final-answer delivery must pass through a disabled delivery gate that refuses final-answer delivery and delivery handoff.',
    },
    {
      key: 'mutationFinalAnswerDeliveryReceiptGate',
      status: 'REFUSED_FINAL_ANSWER_DELIVERY_RECEIPT_DISABLED',
      passed: true,
      blocking: false,
      releaseGateEnabled: false,
      requestCreationEnabled: false,
      pushEnabled: false,
      claimable: false,
      mutationAllowed: false,
      mutationResultAggregationEnabled: false,
      publicationEnabled: false,
      finalAnswerGenerationEnabled: false,
      finalAnswerCompletionEnabled: false,
      finalAnswerDeliveryEnabled: false,
      finalAnswerPersistenceEnabled: false,
      conversationTurnSaveEnabled: false,
      userVisibleCompletionEnabled: false,
      finalResponseHandoffEnabled: false,
      deliveryHandoffEnabled: false,
      deliveryReceiptEnabled: false,
      acknowledgementSaveEnabled: false,
      message: 'Future mutation final-answer delivery receipt must pass through a disabled receipt gate that refuses delivery receipt and acknowledgement.',
    },
    {
      key: 'acknowledgementSaveRefusal',
      status: 'DISABLED_AUDIT_ONLY',
      passed: true,
      blocking: false,
      releaseGateEnabled: false,
      requestCreationEnabled: false,
      pushEnabled: false,
      claimable: false,
      mutationAllowed: false,
      mutationResultAggregationEnabled: false,
      publicationEnabled: false,
      finalAnswerGenerationEnabled: false,
      finalAnswerCompletionEnabled: false,
      finalAnswerDeliveryEnabled: false,
      finalAnswerPersistenceEnabled: false,
      conversationTurnSaveEnabled: false,
      userVisibleCompletionEnabled: false,
      finalResponseHandoffEnabled: false,
      deliveryHandoffEnabled: false,
      deliveryReceiptEnabled: false,
      acknowledgementSaveEnabled: false,
      message: 'Future acknowledgement save must remain explicitly refused until final-answer delivery receipt is enabled.',
    },
  ],
  blockingKeys: [],
  message: 'Local Agent mutation completion prerequisites are modeled, but execution, aggregation, publication, and final-answer generation remain disabled.',
});

assert.equal(view.show, true);
assert.equal(
  view.headerText,
  'mutation completion summary: READY_COMPLETION_DISABLED / learnbot.local-agent.mutation-completion-summary.v1 / prerequisites true / USER_LOCAL_AGENT / receipt REFUSED_FINAL_ANSWER_DELIVERY_RECEIPT_DISABLED / acknowledgement DISABLED_AUDIT_ONLY / acknowledgement save false'
);
assert.equal(
  view.sourceContextText,
  'mutation completion source context: publication gate REFUSED_PUBLICATION_DISABLED / publication schema learnbot.local-agent.mutation-publication-gate.v1 / publication session session-1 / publication user user-1 / publication agent agent-1 / publication workspace workspace-1 / publication READY_PUBLICATION_DISABLED / draft READY_DRAFT_DISABLED / observations 2 / accepted 2 / rejected 0 / missing result risk false / stale index risk true / publication observations OBSERVED / publication count 2 / publication accepted 2 / publication rejected 0 / publication missing result risk false / publication stale index risk true / publication latest ACCEPTED / publication tool patch.apply / publication verification PASSED / publication rollback summary observations OBSERVED / publication rollback summary count 2 / publication rollback summary accepted 2 / publication rollback summary rejected 0 / publication rollback summary missing result risk false / publication rollback summary stale index risk true'
);
assert.equal(
  view.disabledText,
  'mutation completion disabled: release gate false / request creation false / push false / claim false / write helper false / claimable false / mutation false / apply false / test false / rollback restore false / rag freshness false / result aggregation false / publication false / final answer false / completion false / delivery false / persistence false / conversation save false / user-visible completion false / final response handoff false / delivery handoff false / receipt false / acknowledgement save false'
);
assert.deepEqual(view.itemLines, [
  'releaseAttemptReadiness: READY / passed true / blocking false / release gate false / request creation false / push false / claimable false / mutation false / result aggregation false / publication false / final answer false / completion false / delivery false / persistence false / conversation save false / user-visible completion false / final response handoff false / delivery handoff false / receipt false / acknowledgement save false / Latest release attempt must be fresh, complete, and based on passing patch preconditions.',
  'mutationFinalAnswerDeliveryGate: REFUSED_FINAL_ANSWER_DELIVERY_DISABLED / passed true / blocking false / release gate false / request creation false / push false / claimable false / mutation false / result aggregation false / publication false / final answer false / completion false / delivery false / persistence false / conversation save false / user-visible completion false / final response handoff false / delivery handoff false / receipt false / acknowledgement save false / Future mutation final-answer delivery must pass through a disabled delivery gate that refuses final-answer delivery and delivery handoff.',
  'mutationFinalAnswerDeliveryReceiptGate: REFUSED_FINAL_ANSWER_DELIVERY_RECEIPT_DISABLED / passed true / blocking false / release gate false / request creation false / push false / claimable false / mutation false / result aggregation false / publication false / final answer false / completion false / delivery false / persistence false / conversation save false / user-visible completion false / final response handoff false / delivery handoff false / receipt false / acknowledgement save false / Future mutation final-answer delivery receipt must pass through a disabled receipt gate that refuses delivery receipt and acknowledgement.',
  'acknowledgementSaveRefusal: DISABLED_AUDIT_ONLY / passed true / blocking false / release gate false / request creation false / push false / claimable false / mutation false / result aggregation false / publication false / final answer false / completion false / delivery false / persistence false / conversation save false / user-visible completion false / final response handoff false / delivery handoff false / receipt false / acknowledgement save false / Future acknowledgement save must remain explicitly refused until final-answer delivery receipt is enabled.',
]);
assert.equal(view.blockingText, '');
assert.match(view.message, /remain disabled/);

const blocked = buildMutationCompletionSummaryView({
  status: 'BLOCKED_COMPLETION_DISABLED',
  finalAnswerDeliveryEnabled: false,
  deliveryHandoffEnabled: false,
  deliveryReceiptEnabled: false,
  acknowledgementSaveEnabled: false,
  blockingKeys: ['mutationCompletionSummary'],
});
assert.equal(blocked.show, true);
assert.equal(
  blocked.disabledText,
  'mutation completion disabled: delivery false / delivery handoff false / receipt false / acknowledgement save false'
);
assert.equal(blocked.blockingText, 'mutation completion blocking keys: mutationCompletionSummary');

const hidden = buildMutationCompletionSummaryView(null);
assert.equal(hidden.show, false);
assert.deepEqual(hidden.itemLines, []);
