import assert from 'node:assert/strict';
import { buildMutationFinalResponseHandoffGateView } from './mutationFinalResponseHandoffGate.js';

const view = buildMutationFinalResponseHandoffGateView({
  schema: 'learnbot.local-agent.mutation-final-response-handoff-gate.v1',
  status: 'REFUSED_FINAL_RESPONSE_HANDOFF_DISABLED',
  userVisibleCompletionReady: true,
  prerequisitesPassed: true,
  executionTarget: 'USER_LOCAL_AGENT',
  finalResponseHandoffPolicy: 'DISABLED_AUDIT_ONLY',
  deliveryHandoffEnabled: false,
  sourceFinalAnswerUserVisibleCompletionGateStatus: 'REFUSED_FINAL_ANSWER_USER_VISIBLE_COMPLETION_DISABLED',
  sourceFinalAnswerUserVisibleCompletionGateSchema: 'learnbot.local-agent.mutation-final-answer-user-visible-completion-gate.v1',
  sourceFinalAnswerUserVisibleCompletionGatePublicationGateStatus: 'REFUSED_PUBLICATION_DISABLED',
  sourceFinalAnswerUserVisibleCompletionGatePublicationGateSchema: 'learnbot.local-agent.mutation-publication-gate.v1',
  sourceFinalAnswerUserVisibleCompletionGatePublicationGateSessionId: 'session-1',
  sourceFinalAnswerUserVisibleCompletionGatePublicationGateUserId: 'user-1',
  sourceFinalAnswerUserVisibleCompletionGatePublicationGateAgentId: 'agent-1',
  sourceFinalAnswerUserVisibleCompletionGatePublicationGateWorkspaceId: 'workspace-1',
  sourceFinalAnswerUserVisibleCompletionGatePublicationBoundaryStatus: 'READY_PUBLICATION_DISABLED',
  sourceFinalAnswerUserVisibleCompletionGatePublicationBoundaryPrerequisitesPassed: true,
  sourceFinalAnswerUserVisibleCompletionGatePublicationBoundaryDraftStatus: 'READY_DRAFT_DISABLED',
  sourceFinalAnswerUserVisibleCompletionGatePublicationBoundaryDraftSections: ['changedFiles', 'verificationOutcome', 'rollbackState', 'ragFreshnessState'],
  sourceFinalAnswerUserVisibleCompletionGateAcceptedObservationSummaryStatus: 'OBSERVED',
  sourceFinalAnswerUserVisibleCompletionGateAcceptedObservationCount: 2,
  sourceFinalAnswerUserVisibleCompletionGateAcceptedObservationAcceptedCount: 2,
  sourceFinalAnswerUserVisibleCompletionGateAcceptedObservationRejectedCount: 0,
  sourceFinalAnswerUserVisibleCompletionGateMissingMutationResultRiskVisible: false,
  sourceFinalAnswerUserVisibleCompletionGateStaleIndexRiskVisible: true,
  sourceFinalAnswerUserVisibleCompletionGatePublicationAcceptedObservationSummaryStatus: 'OBSERVED',
  sourceFinalAnswerUserVisibleCompletionGatePublicationAcceptedObservationCount: 2,
  sourceFinalAnswerUserVisibleCompletionGatePublicationAcceptedObservationAcceptedCount: 2,
  sourceFinalAnswerUserVisibleCompletionGatePublicationAcceptedObservationRejectedCount: 0,
  sourceFinalAnswerUserVisibleCompletionGatePublicationMissingMutationResultRiskVisible: false,
  sourceFinalAnswerUserVisibleCompletionGatePublicationStaleIndexRiskVisible: true,
  sourceFinalAnswerUserVisibleCompletionGatePublicationLatestAcceptedObservationStatus: 'ACCEPTED',
  sourceFinalAnswerUserVisibleCompletionGatePublicationLatestAcceptedObservationToolName: 'patch.apply',
  sourceFinalAnswerUserVisibleCompletionGatePublicationLatestAcceptedObservationVerificationStatus: 'PASSED',
  sourceFinalAnswerUserVisibleCompletionGatePublicationRollbackAcceptedObservationSummaryStatus: 'OBSERVED',
  sourceFinalAnswerUserVisibleCompletionGatePublicationRollbackAcceptedObservationSummaryObservationCount: 2,
  sourceFinalAnswerUserVisibleCompletionGatePublicationRollbackAcceptedObservationSummaryAcceptedCount: 2,
  sourceFinalAnswerUserVisibleCompletionGatePublicationRollbackAcceptedObservationSummaryRejectedCount: 0,
  sourceFinalAnswerUserVisibleCompletionGatePublicationRollbackAcceptedObservationSummaryMissingMutationResultRiskVisible: false,
  sourceFinalAnswerUserVisibleCompletionGatePublicationRollbackAcceptedObservationSummaryStaleIndexRiskVisible: true,
  sourceRequestId: 'request-123',
  releaseAttemptId: 'attempt-1234567890',
  sessionId: 'session-1',
  userId: 'user-1',
  agentId: 'agent-1',
  workspaceId: 'workspace-1',
  expectedResultCount: 4,
  completedResultCount: 0,
  acceptedResultCount: 0,
  rejectedResultCount: 0,
  intakePersistedResultCount: 0,
  finalResponseHandoffEnabled: false,
  deliveryHandoffEnabled: false,
  deliveryReceiptEnabled: false,
  acknowledgementSaveEnabled: false,
  finalAnswerDeliveryEnabled: false,
  userVisibleCompletionEnabled: false,
  conversationTurnSaveEnabled: false,
  finalAnswerPersistenceEnabled: false,
  finalAnswerCompletionEnabled: false,
  finalAnswerGenerationEnabled: false,
  publicationEnabled: false,
  mutationResultAggregationEnabled: false,
  ragFreshnessUpdateEnabled: false,
  rollbackFallbackExecutionEnabled: false,
  intakePersistenceEnabled: false,
  acceptedObservationPersistenceEnabled: false,
  postExecutionObservationEnabled: false,
  completedResultPersistenceEnabled: false,
  observationAcceptanceEnabled: false,
  releaseGateEnabled: false,
  requestCreationEnabled: false,
  pushEnabled: false,
  claimEnabled: false,
  executionEnabled: false,
  writeHelperEnabled: false,
  claimable: false,
  mutationAllowed: false,
  applyEnabled: false,
  testEnabled: false,
  rollbackRestoreEnabled: false,
  policyChecks: [
    {
      key: 'mutationFinalAnswerUserVisibleCompletionGate',
      status: 'REFUSED_FINAL_ANSWER_USER_VISIBLE_COMPLETION_DISABLED',
      passed: true,
      blocking: false,
      requestCreationEnabled: false,
      pushEnabled: false,
      claimEnabled: false,
      executionEnabled: false,
      writeHelperEnabled: false,
      claimable: false,
      mutationAllowed: false,
      publicationEnabled: false,
      finalAnswerGenerationEnabled: false,
      finalAnswerCompletionEnabled: false,
      finalAnswerDeliveryEnabled: false,
      finalAnswerPersistenceEnabled: false,
      conversationTurnSaveEnabled: false,
      userVisibleCompletionEnabled: false,
      finalResponseHandoffEnabled: false,
      deliveryHandoffEnabled: false,
      deliveryReceiptEnabled: false,
      acknowledgementSaveEnabled: false,
      message: 'A disabled final-answer user-visible completion gate must refuse user-visible completion before final-response handoff can be considered.',
    },
    {
      key: 'finalResponseHandoffPolicy',
      status: 'DISABLED',
      passed: false,
      blocking: true,
      requestCreationEnabled: false,
      pushEnabled: false,
      claimEnabled: false,
      executionEnabled: false,
      writeHelperEnabled: false,
      claimable: false,
      mutationAllowed: false,
      publicationEnabled: false,
      finalAnswerGenerationEnabled: false,
      finalAnswerCompletionEnabled: false,
      finalAnswerDeliveryEnabled: false,
      finalAnswerPersistenceEnabled: false,
      conversationTurnSaveEnabled: false,
      userVisibleCompletionEnabled: false,
      finalResponseHandoffEnabled: false,
      deliveryHandoffEnabled: false,
      deliveryReceiptEnabled: false,
      acknowledgementSaveEnabled: false,
      message: 'Mutation final-response handoff and delivery handoff are disabled.',
    },
    {
      key: 'finalResponseHandoff',
      status: 'DISABLED',
      passed: false,
      blocking: true,
      requestCreationEnabled: false,
      pushEnabled: false,
      claimEnabled: false,
      executionEnabled: false,
      writeHelperEnabled: false,
      claimable: false,
      mutationAllowed: false,
      publicationEnabled: false,
      finalAnswerGenerationEnabled: false,
      finalAnswerCompletionEnabled: false,
      finalAnswerDeliveryEnabled: false,
      finalAnswerPersistenceEnabled: false,
      conversationTurnSaveEnabled: false,
      userVisibleCompletionEnabled: false,
      finalResponseHandoffEnabled: false,
      deliveryHandoffEnabled: false,
      deliveryReceiptEnabled: false,
      acknowledgementSaveEnabled: false,
      message: 'No final response may be handed off while final-response handoff is disabled.',
    },
    {
      key: 'finalAnswerDelivery',
      status: 'DISABLED',
      passed: false,
      blocking: true,
      requestCreationEnabled: false,
      pushEnabled: false,
      claimEnabled: false,
      executionEnabled: false,
      writeHelperEnabled: false,
      claimable: false,
      mutationAllowed: false,
      publicationEnabled: false,
      finalAnswerGenerationEnabled: false,
      finalAnswerCompletionEnabled: false,
      finalAnswerDeliveryEnabled: false,
      finalAnswerPersistenceEnabled: false,
      conversationTurnSaveEnabled: false,
      userVisibleCompletionEnabled: false,
      finalResponseHandoffEnabled: false,
      deliveryHandoffEnabled: false,
      deliveryReceiptEnabled: false,
      acknowledgementSaveEnabled: false,
      message: 'No final answer may be delivered while final-response handoff is disabled.',
    },
    {
      key: 'userVisibleCompletion',
      status: 'DISABLED',
      passed: false,
      blocking: true,
      requestCreationEnabled: false,
      pushEnabled: false,
      claimEnabled: false,
      executionEnabled: false,
      writeHelperEnabled: false,
      claimable: false,
      mutationAllowed: false,
      publicationEnabled: false,
      finalAnswerGenerationEnabled: false,
      finalAnswerCompletionEnabled: false,
      finalAnswerDeliveryEnabled: false,
      finalAnswerPersistenceEnabled: false,
      conversationTurnSaveEnabled: false,
      userVisibleCompletionEnabled: false,
      finalResponseHandoffEnabled: false,
      deliveryHandoffEnabled: false,
      deliveryReceiptEnabled: false,
      acknowledgementSaveEnabled: false,
      message: 'No user-visible completion may be marked while final-response handoff is disabled.',
    },
  ],
  blockingKeys: [
    'finalResponseHandoffPolicy',
    'finalResponseHandoff',
    'finalAnswerDelivery',
    'userVisibleCompletion',
    'finalResponseHandoffEnabled',
    'deliveryHandoffEnabled',
    'deliveryReceiptEnabled',
    'acknowledgementSaveEnabled',
    'finalAnswerDeliveryEnabled',
    'userVisibleCompletionEnabled',
    'conversationTurnSaveEnabled',
    'finalAnswerPersistenceEnabled',
    'finalAnswerCompletionEnabled',
    'finalAnswerGenerationEnabled',
    'mutationAllowed',
  ],
  message: 'Local Agent mutation final-response handoff is explicitly refused: no final response is handed off and no final answer is delivered.',
});

assert.equal(view.show, true);
assert.equal(
  view.headerText,
  'mutation final-response handoff gate: REFUSED_FINAL_RESPONSE_HANDOFF_DISABLED / learnbot.local-agent.mutation-final-response-handoff-gate.v1 / user-visible completion ready true / prerequisites true / USER_LOCAL_AGENT / policy DISABLED_AUDIT_ONLY / delivery handoff false / final-answer user-visible completion status REFUSED_FINAL_ANSWER_USER_VISIBLE_COMPLETION_DISABLED / learnbot.local-agent.mutation-final-answer-user-visible-completion-gate.v1'
);
assert.equal(
  view.idsText,
  'mutation final-response handoff ids: source request-123 / release attempt- / session session-1 / user user-1 / agent agent-1 / workspace workspace-1'
);
assert.equal(
  view.countsText,
  'mutation final-response handoff counts: expected 4 / completed 0 / accepted 0 / rejected 0 / intake persisted 0'
);
assert.equal(
  view.sourceContextText,
  'mutation final-response handoff source context: publication gate REFUSED_PUBLICATION_DISABLED / publication schema learnbot.local-agent.mutation-publication-gate.v1 / publication session session-1 / publication user user-1 / publication agent agent-1 / publication workspace workspace-1 / publication boundary READY_PUBLICATION_DISABLED / publication prerequisites true / draft READY_DRAFT_DISABLED / sections changedFiles, verificationOutcome, rollbackState, ragFreshnessState / observations OBSERVED / observed 2 / accepted 2 / rejected 0 / missing result risk false / stale index risk true / publication observations OBSERVED / publication count 2 / publication accepted 2 / publication rejected 0 / publication missing result risk false / publication stale index risk true / publication latest ACCEPTED / publication tool patch.apply / publication verification PASSED / publication rollback summary observations OBSERVED / publication rollback summary count 2 / publication rollback summary accepted 2 / publication rollback summary rejected 0 / publication rollback summary missing result risk false / publication rollback summary stale index risk true'
);
assert.equal(
  view.disabledText,
  'mutation final-response handoff disabled: final response handoff false / delivery handoff false / delivery receipt false / acknowledgement save false / delivery false / user-visible completion false / conversation save false / persistence false / completion false / final answer false / publication false / result aggregation false / rag freshness false / rollback fallback false / intake persistence false / accepted observation persistence false / post-execution observation false / result persistence false / acceptance false / release gate false / request creation false / push false / claim false / execution false / write helper false / claimable false / mutation false / apply false / test false / rollback restore false'
);
assert.deepEqual(view.policyLines, [
  'final-response handoff policy mutationFinalAnswerUserVisibleCompletionGate: REFUSED_FINAL_ANSWER_USER_VISIBLE_COMPLETION_DISABLED / passed true / blocking false / request creation false / push false / claim false / execution false / write helper false / claimable false / mutation false / publication false / final answer false / completion false / delivery false / persistence false / conversation save false / user-visible completion false / final response handoff false / delivery handoff false / delivery receipt false / acknowledgement save false / A disabled final-answer user-visible completion gate must refuse user-visible completion before final-response handoff can be considered.',
  'final-response handoff policy finalResponseHandoffPolicy: DISABLED / passed false / blocking true / request creation false / push false / claim false / execution false / write helper false / claimable false / mutation false / publication false / final answer false / completion false / delivery false / persistence false / conversation save false / user-visible completion false / final response handoff false / delivery handoff false / delivery receipt false / acknowledgement save false / Mutation final-response handoff and delivery handoff are disabled.',
  'final-response handoff policy finalResponseHandoff: DISABLED / passed false / blocking true / request creation false / push false / claim false / execution false / write helper false / claimable false / mutation false / publication false / final answer false / completion false / delivery false / persistence false / conversation save false / user-visible completion false / final response handoff false / delivery handoff false / delivery receipt false / acknowledgement save false / No final response may be handed off while final-response handoff is disabled.',
  'final-response handoff policy finalAnswerDelivery: DISABLED / passed false / blocking true / request creation false / push false / claim false / execution false / write helper false / claimable false / mutation false / publication false / final answer false / completion false / delivery false / persistence false / conversation save false / user-visible completion false / final response handoff false / delivery handoff false / delivery receipt false / acknowledgement save false / No final answer may be delivered while final-response handoff is disabled.',
  'final-response handoff policy userVisibleCompletion: DISABLED / passed false / blocking true / request creation false / push false / claim false / execution false / write helper false / claimable false / mutation false / publication false / final answer false / completion false / delivery false / persistence false / conversation save false / user-visible completion false / final response handoff false / delivery handoff false / delivery receipt false / acknowledgement save false / No user-visible completion may be marked while final-response handoff is disabled.',
]);
assert.equal(
  view.blockingText,
  'mutation final-response handoff blocking keys: finalResponseHandoffPolicy, finalResponseHandoff, finalAnswerDelivery, userVisibleCompletion, finalResponseHandoffEnabled, deliveryHandoffEnabled, deliveryReceiptEnabled, acknowledgementSaveEnabled, finalAnswerDeliveryEnabled, userVisibleCompletionEnabled, conversationTurnSaveEnabled, finalAnswerPersistenceEnabled, finalAnswerCompletionEnabled, finalAnswerGenerationEnabled, mutationAllowed'
);
assert.match(view.message, /explicitly refused/);

const hidden = buildMutationFinalResponseHandoffGateView(null);
assert.equal(hidden.show, false);
assert.deepEqual(hidden.policyLines, []);

const blocked = buildMutationFinalResponseHandoffGateView({
  policyChecks: null,
  blockingKeys: null,
  message: 'Local Agent mutation final-response handoff is blocked because the disabled final-answer user-visible completion gate is incomplete.',
});
assert.equal(blocked.show, true);
assert.equal(
  blocked.headerText,
  'mutation final-response handoff gate: BLOCKED_FINAL_RESPONSE_HANDOFF_DISABLED'
);
assert.deepEqual(blocked.policyLines, []);
assert.equal(blocked.blockingText, '');
assert.match(blocked.message, /blocked/);
