ALTER TABLE indexing_jobs
    ADD COLUMN IF NOT EXISTS added_files INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS modified_files INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS unchanged_files INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS deleted_files INTEGER NOT NULL DEFAULT 0;
