package com.learnbot.service.agentloop;

public enum CodeAgentLoopState {
    CREATED,
    READ_ONLY_OBSERVATION_QUEUED,
    WAITING_FOR_LOCAL_AGENT,
    OBSERVATION_RECEIVED,
    PATCH_PROPOSAL_CREATING,
    PATCH_PROPOSAL_READY,
    WAITING_FOR_APPROVAL,
    APPROVED_HELD,
    RELEASE_PRECHECK_REQUIRED,
    WAITING_FOR_RELEASE_GATE,
    RELEASED_FOR_EXECUTION,
    PATCH_APPLY_RUNNING,
    TEST_RUNNING,
    VERIFYING_GIT_STATUS,
    ROLLBACK_REQUIRED,
    ROLLBACK_RUNNING,
    FINAL_REPORT_READY,
    COMPLETED,
    FAILED,
    STOPPED
}
