package com.learnbot.service.agentloop;

public enum CodeAgentLoopEvent {
    RUN_CREATED,
    READ_ONLY_REQUEST_QUEUED,
    LOCAL_AGENT_RESULT_SUCCEEDED,
    LOCAL_AGENT_RESULT_FAILED,
    LOCAL_AGENT_RESULT_REJECTED,
    NEXT_DECISION_RECORDED,
    PATCH_APPROVAL_CREATED,
    APPROVED,
    DENIED,
    RELEASE_FRESH_OBSERVATIONS_QUEUED,
    RELEASE_FRESH_OBSERVATIONS_COMPLETE,
    RELEASE_READINESS_REFRESHED,
    RELEASE_BOUNDARY_REFUSED,
    RELEASED,
    PATCH_APPLIED,
    PATCH_FAILED,
    TEST_RUNNING,
    TEST_PASSED,
    TEST_FAILED,
    GIT_STATUS_VERIFIED,
    ROLLBACK_REQUIRED,
    ROLLBACK_SUCCEEDED,
    APPROVED_EXECUTION_FLOW_COMPLETED,
    STOP_RECORDED,
    UNKNOWN_OBSERVATION
}
